In [1]:
import pandas as pd

purchase_real = pd.read_csv('C:/cakd7/2차 프로젝트/MERGE_PURPRD_PRICE_2_DATA_TABLE.csv')
purchase_real

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT
0,17485,B,8919510,식품/생활,식품,샐러드채소,양상추,일용품,2015,4,3,저가,2000
1,17485,B,8919510,식품/생활,식품,김치채소,무우,일용품,2015,4,3,저가,1250
2,17485,B,8919510,식품/생활,식품,일반한우,한우양지,일용품,2015,4,3,고가,23790
3,17485,B,8919510,식품/생활,식품,포도,캠벨포도,일용품,2015,4,3,중가,25600
4,17485,B,8919510,식품/생활,식품,메론,머스크메론,일용품,2015,4,3,중가,12800
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28593025,5786,B,7784894,식품/생활,식품,스낵,일반스낵,일용품,2014,1,2,중가,490
28593026,14026,B,7784900,식품/생활,식품,족발,냉장족발,일용품,2014,1,2,중가,4000
28593027,16612,C,9500419,식품/생활,식품,기타축산,돼지양념육,일용품,2014,2,3,중가,7900
28593028,7565,C,10737145,식품/생활,식품,우유,일반우유,일용품,2014,2,4,저가,5200
28593029,19295,A,3332011,식품/생활,식품,농산물,유기농채소,일용품,2014,2,4,중가,2840

In [79]:
purchase_real.columns

Index(['CUSTNO', 'ASSO', 'RNO', 'BBCL', 'BCL', 'MCL', 'SCL', 'TYPE', 'PURYEAR',
       'HALF_YEAR', 'QUARTER', 'PRICE_TYPE', 'PURAMT', 'Q_year'],
      dtype='object')

In [85]:
purchase_real['BBCL'].unique()

array(['식품/생활', '의류/이미용', '침구/주방', '교육문화/아동', '가구인테리어/잡화', '가전/레저취미/멀티샵'],
      dtype=object)

In [87]:
for BBCL in purchase_real['BBCL'].unique():
    print('***', BBCL)
    print(purchase_real[purchase_real['BBCL'] == BBCL]['MCL'].unique())
    print('\n')

*** 식품/생활
['샐러드채소' '김치채소' '일반한우' '포도' '메론' '바나나' '미역/다시마' '양념채소' '뿌리채소' '구색과일' '흰우유'
 '요구르트' '균일가' '탄산음료' '가공우유' '사과' '고등어/삼치' '냉동간식' '냉장식사HMR' '조미오징어' '소스류'
 '두유' '스낵' '포장반찬' '잎채소' '식용유지' '어묵맛살' '브랜드돼지고기' '마른김' '계란' '분유' '커피차음료'
 '세탁세제' '유아위생용품' '복숭아' '선식' '조미김' '맥주' '소주' '국산게/갈치' '생수' '냉장음료' '파이' '간식'
 '건전지' '간편요리' '두부' '오렌지' '키위' '수입돼지고기' '물티슈' '차별화돼지고기' '전통과자' '콩나물' '건과'
 '푸드코트' '편의시설' '버섯' '통조림' '비스켓' '수입과자' '냉동만두' '딸기' '생선회' '수입조미' '묵/즉석참기름'
 '햄' '브랜드빵' '치즈' '유가공' '떡' '면류' '액상조미료' '꿀' '토마토' '열매채소' '베이커리' '튀김'
 '소금/설탕류' '차' '화장지' '단무지류' '대중선어' '해조류' '캔디' '과채음료' '청소용품' '간편조리식품' '냉장면류'
 '전통주' '욕실용품' '키위/석류' '빵' '간편채소' '닭고기' '조개' '조개살' '냉장반찬' '냉동과일' '라면'
 '샐러드/간편채소' '장류' '여성위생용품' '아이스크림' '수박' '종량제봉투' '가루' '감귤' '체리' '잡곡' '버섯류'
 '친환경채소' '해물연체류' '잡곡류' '우육' '간편조리' '햄소시지' '과채과일' '열대과일' '껌' '즉석참기름' '소시지'
 '냉동HMR' '김가공품' '새우' '수입갈치' '특산물행사' '양념류' '기능성음료' '와인' '돼지고기' '수입기타과일'
 '시리얼' '양념육' '포도/체리' '건강식품' '주방세제' '커피' '즉석도정미' '묵' '초콜릿' '이온음료' '오렌지과일기타'
 '파인애플' '일반욕실용품' '가공란' '생리대' '간편조리생선' '유제품' '과실과일' '친환경과일' '반찬류' '야외용품'
 '피자' '주거세제' '밥류' '튀김조리' '특산물' '나물' '족발' '조미료' '수입육' '마른안주' '섬유유연제'
 '호주산소고기' '오징어' '원두커피' '쥐치포' '시즌차' '자두' '시즌행사' '밥죽류' '프리미엄과자' 'LOCAL잎채소'
 '간식용과자' '자몽' '복합조미료' '간편조리행사' '잼' '레스토랑' '디저트' '수도용품' '브랜드한우' '즉석구이김'
 '참외' '기저귀' '수입감귤과일' '육가공품' '먹거리행사' '김/초밥' '도시락' '국산과일선물세트' '냉장간편식HMR'
 '향신료' '가공양곡' '수입포도' '기능성건강' '야외/시즌용품' '중식' '한식' '양식' '안주' '수입기타생선' '배'
 '보수용품' '조리반찬' '탈취제' '건오징어' '인스턴트커피' '홍인삼' '조미선물세트' '커피선물세트' '수입고등어'
 '김선물세트' '오리고기' '구이' '꽁치/가자미' '멸치' '전구' '맛집행사' '미국산소고기' '규격RTC'
 'LOCAL김치채소' '냉동대용식' '멸치건명태' '양곡' '감' '가공식품' '농산물' '젓갈/반찬' '주류' '축산가공'
 '차/커피' '육류' '수산품' '육포' '한방식재류' '밤' '수입연어' '김치채소류' '국내산돈육' '건면' '국산과일'
 '두채류' '선어류' '건어류' '건어가공' '냉장농산' '생리용품' '수입과일' '과채류' '근채류' '기타음주류' '담배'
 '냉장축산' '엽채류' '계란류' '우유' '견과류' '커피류' '차류' '청소욕실용품' '발효유' '쿠키케이크' '캔디껌류'
 '냉장수산' '냉장간식MS' '냉장식사MS' '병통조림' '식용유' '주방주거세제' '감미료' '국내산계육' '초콜렛' '만두'
 '즉석식품' '기타조리식품' '치즈버터' '차음료' '나물류' '선어가공' '커피음료' '가공건식품' '구강용품' '씨리얼'
 '가공분말류' '두발용품' '유아용품' '양채류' '냉동수산물' '생활한방' '젓갈류' '김치류' '개인위생용품' '구강케어'
 '여성용품' '남성용품' '냉장규격생선' '미용티슈' '표백제' '기타구색생선' '자동차 편의용품' '국내산우육' '기타축산'
 '케첩마요네즈' '간편간식' '해초류' '간식조리' '양주' '생활잡화' '과자' '음료' '방향/제습/탈취제' '건강기능식품'
 '화장지/티슈' '일반의약외품' '기기' '먹거리' '냉장기타MS' '식사류' '냉동MS' '위생용품' '수입우육' '반건생선'
 '키친타올' '안전용품' '패브릭욕실용품' 'Fast Food' '해물류' '기타수산' '블루베리' '레몬' '판매시설'
 '자동차 정비용품' '자동차 액세서리' '구이찜조리' '한과' '교환/보수용품' '열대과일기타' '세차용품' '자동차방향제/소취제'
 '이유식/유아간식' '일식' '전통간식' '냉동규격해물' '인스턴트선물세트' '수납용품' '청소편의도구' '카페' '수입음료'
 '기타회' '비타민' '포장젓갈' '대구' '살충제' '제습제' '컨세션' '자동차 청소용품' '카시트/매트' '황태'
 '밀대/걸레' '전기용품' '굴비' '선물세트' '즉석구이안주' '석류' '공구' '한방차' '해초' '연체' '망고'
 '브랜드푸드몰' '건과일' '식자재' '시니어위생용품' '세탁용품' '조기/명태' '순대' '휴지통' '냉동규격생선' '생선초밥'
 '유아세제' '시즌반찬' '휴대폰용품' '장착용품' '매트' '분식' '수입돈육' '대용식' '종합과자' '수입게'
 '자동차장식용품' '냉동가공' '반찬' '한우선물세트' '포장반찬HMR' '멸치황태미역선물세트' '도미/민어' '건강선물세트'
 '천연조미료' '오렌지과일선물세트' '기타국소고기' '이벤트조리' '약초' '프리미엄매트' '패스트푸드' 'DIY욕실용품'
 '생선선물세트' '차선물세트' '수입육선물세트' '선식류' '데일리처분' '굴비/반건생선선물세트' '냉장햄세트' '마른안주선물세트'
 '열대과일선물세트' '규격생선선물세트' '브랜드조리' '해물선물세트' '주유소' '온라인규격/간편조리생선' '자동차처분'
 '오토바이용품' '온라인해물연체' '온라인잎/샐러드채소' '온라인양념/뿌리채소' '온라인잡곡선식' '온라인버섯/열매채소'
 '온라인저장과일' '온라인돼지고기']


*** 의류/이미용
['H&B선물세트' '란제리' '기초화장품' '색조화장품' '시티캐주얼' '여성캐주얼브랜드' '이지캐주얼브랜드' '남성스포츠PB'
 '구강용품' '바디케어' '남성행사' '비즈니스정장' '드럭스토어' '기능헤어케어' '덧신' '바디용품' '헤어스타일링'
 '여성이지캐주얼' '면도용품' '아동내의' '스트리트편집샵' '훼이셜케어' '미용소품' '캐주얼' '화장품' '커리어'
 '아이메이크업' '풋/핸드케어' '디자이너' '셔츠' '남성 트랜디' '트래디셔널' '기타의류' '란제리/내의' '집중케어'
 '헤어케어' '핸드/풋케어' '클렌징' '베이직케어' '립메이크업' '선케어' '남성' '네일메이크업' '여성' '남성케어'
 '계절팩' '베이스메이크업' '남성캐주얼' '베이비케어' '시티웨어' '모피/피혁' '의류잡화' '아로마' '홈웨어' '복합샵'
 '성인내의' '남성정장' '란제리브랜드' '일반헤어케어' '스타킹' '스킨케어' '여성PB' '화장품브랜드샵' '언더웨어행사'
 '미시캐주얼' '국내화장품' '개인위생용품' '남성브랜드' '행사' '미용잡화' '남성베이직' '남성스포츠' '남성이지캐주얼'
 '남성시즌행사' '교복' '여성베이직' '남성어덜트캐주얼' '수입브랜드' '마담/어덜트' '여성특정' '여성NPB' '병행수입'
 '남성스포츠특정' '남성스포츠NPB' '블라우스' '웨딩' '온라인화장품']


*** 침구/주방
['조리용기' '주방정리' '주방시즌/균일가' '음식저장/보관' '수예소품' '커튼류' '브랜드침구' '성인침구' '음식조리'
 '조리도구' '수예시즌' '그릇/수저' '유아식기' '아동침구' '침구/수예' '주방용품' '주방가전' '식기' '성인침구류'
 '아동침구류']


*** 교육문화/아동
['오피스용품' '미술용품' '예능학용품' '파티/팬시/시즌' '필기도구' '아동복합샵' '유아브랜드' '아동브랜드' '노트/지류'
 'EDUCATION 1' 'BOYS 1' '서적' '교육보조재' '시즌행사' '파티/팬시' '교육' 'BABY/INFANT'
 'GIRLS' '유/아동서적' '아동' '문구/팬시' 'SPORTS/OUTDOOR' 'BOYS 2' 'EDUCATION 2'
 '유아용품' '유아동PB' '노트' '유아토들러' '유아동용품' '남아' '일반서적' 'VIDEOGAME' '주니어스포츠'
 '주니어웨어' '음반영상' '영상' '아동행사' '유아동특정' '음반' '유아동NPB']


*** 가구인테리어/잡화
['남성양말' '드레스화브랜드' '모자' '시즌잡화' '운동화' '캐주얼화브랜드' '미입점행사' '아동슈즈' '샌들슬리퍼'
 '여성양말' '일용잡화' '구두' '섬유잡화' '명품' '가정잡화' '액세서리' '소가구' '피혁잡화' '우산/양산류' '양말류'
 '파티/팬시용품' '보석' '준보석/시계' '아동양말' '스포츠슈즈' '잡화멀티샵' '가방' '준보석' '장식용품' '양말선물세트'
 '우산/양산' '보수용품' '가구' '조명/전구' '조명기구' 'NB구두' '슈즈행사' '시즌슈즈' '피혁토탈' 'TRAVEL'
 '장갑' '양말' '가방브랜드' '캐주얼슈즈' '의자' '피혁브랜드' '가구/인테리어샵' '주니어양말' '시계' '여행용품'
 '벽지류' '의자/상' '스카프' '슈즈용품' '남성구두' '아동화브랜드' '상' '지갑/벨트' '썬글라스' '제기용품' '핸드백'
 '시즌토탈' '벨트' '여성구두' '테이블' '지갑' '아웃도어퍼니처' '온라인양말']


*** 가전/레저취미/멀티샵
['스포츠NB' '애견용품' '스포츠웨어' '고양이용품' '수족관용품' '브랜드' '스포츠' '문화용품' '전기전자' '동물병원'
 '골프용품' '통신/컴퓨터' '대형가전' '피트니스' '전기용품' '레저취미' '소형가전' '라켓스포츠' '헬스용품'
 '애완/동물용품' '구기용품' '스포츠ACC' '시즌행사' '건강가전' '생활소형가전' '시니어건강용품' '시즌/건강가전'
 '원예용품' '덴탈케어' '전기요/장판' '이동통신' '컴퓨터주변기기' '밥솥' '등산' '수영복' '워터스포츠' '롤러보드'
 '캠핑' '스포츠의류' '청소기' '스키' '자전거' '골프' '윈터스포츠' '기타' '기타음향기기' '전기포트' '악기'
 '믹서기' 'NAVI/하이패스' '기타주방가전' 'TV' '세탁기' '조리기' '주방가전' '오디오' '낚시' '전자/전기'
 '가습기' '전화기/팩스' '히터기' '커피메이커/머신' '카메라/캠코더' 'PC' '김치냉장고' '공기청정기' 'MP3/PMP'
 '냉장고' '선풍기' '에어컨' '전기면도기' 'DVD' '전자학습기' '건강디지털기기' '스포츠브랜드편집' '전자악기'
 '소형음향기기' '홈시어터' '주방소형가전' '정수기']

In [89]:
for BBCL in purchase_real['BBCL'].unique():
    print('***', BBCL)
    display(purchase_real[purchase_real['BBCL'] == BBCL].sort_values('PURAMT', ascending = False)[:20])
    print('\n')

*** 식품/생활

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
12002535,7801,A,5526155,식품/생활,식품,주류,주류,일용품,2015,4,4,고가,93654000,2015_4
217096,3890,A,1232704,식품/생활,식품,주류,주류,일용품,2014,1,1,고가,51098000,2014_1
26876794,7957,B,6778166,식품/생활,식품,분유,분유,선매품,2014,1,1,고가,48112000,2014_1
25438420,7957,B,8535920,식품/생활,식품,분유,분유,선매품,2014,1,1,고가,48060000,2014_1
21809846,7842,A,3884350,식품/생활,식품,수산품,생선,일용품,2015,3,1,고가,34116000,2015_1
14902589,7957,B,6786354,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,30125000,2014_2
26910485,7957,B,7027840,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,30043200,2014_2
26880840,7957,B,7030264,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,30043200,2014_2
1589931,7957,B,8343772,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,30000000,2014_2
25499298,7957,B,7039125,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,30000000,2014_2
2711212,7957,B,7030460,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,29417300,2014_2
4033578,7801,A,4391412,식품/생활,식품,주류,주류,일용품,2015,3,2,고가,28760000,2015_2
26064171,7957,B,7044103,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,28625000,2014_2
25322725,7957,B,6838341,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,28393100,2014_2
16694147,7957,B,8535441,식품/생활,식품,분유,분유,선매품,2014,1,1,고가,27780000,2014_1
4254771,7957,B,8324389,식품/생활,식품,분유,분유,선매품,2014,1,1,고가,27680000,2014_1
25096899,7801,A,5412258,식품/생활,식품,주류,주류,일용품,2015,4,4,고가,27000000,2015_4
27301761,7957,B,6836177,식품/생활,식품,분유,분유,선매품,2014,1,1,고가,27000000,2014_1
20820083,7957,B,8537194,식품/생활,식품,분유,분유,선매품,2014,1,1,고가,26100000,2014_1
28507876,7957,B,6838082,식품/생활,식품,분유,분유,선매품,2014,1,2,고가,25605000,2014_2

*** 의류/이미용

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
18748969,17129,A,3569101,의류/이미용,의류,트래디셔널,타미힐피거상품군,선매품,2015,3,1,중가,93166350,2015_1
10603436,8079,A,2220608,의류/이미용,이미용,화장품,색조 화장품,선매품,2014,1,2,고가,82800000,2014_2
2414533,8888,A,4434192,의류/이미용,의류,캐주얼,수입브릿지,선매품,2015,3,2,중가,69046650,2015_2
2414532,8888,A,4434191,의류/이미용,의류,캐주얼,수입브릿지,선매품,2015,3,2,중가,69046650,2015_2
22978021,17129,A,2938321,의류/이미용,의류,캐주얼,global SPA,선매품,2014,2,4,중가,53320700,2014_4
22978022,17129,A,2938322,의류/이미용,의류,캐주얼,global SPA,선매품,2014,2,4,중가,53320700,2014_4
22978023,17129,A,2938323,의류/이미용,의류,캐주얼,global SPA,선매품,2014,2,4,중가,53320700,2014_4
22978024,17129,A,2938324,의류/이미용,의류,캐주얼,global SPA,선매품,2014,2,4,중가,53320700,2014_4
22978025,17129,A,2938325,의류/이미용,의류,캐주얼,global SPA,선매품,2014,2,4,중가,53320700,2014_4
8058768,8994,A,3439973,의류/이미용,의류,모피/피혁,모피,사치품,2015,3,1,고가,46796400,2015_1
27401471,258,A,5247655,의류/이미용,의류,남성정장,마에스트로,선매품,2015,4,4,고가,46267410,2015_4
18748967,17129,A,3569099,의류/이미용,의류,트래디셔널,타미힐피거상품군,선매품,2015,3,1,중가,41825880,2015_1
28052129,8994,A,3224959,의류/이미용,의류,캐주얼,캐릭터캐주얼,선매품,2014,2,4,중가,41529630,2014_4
22978019,17129,A,2938319,의류/이미용,의류,캐주얼,global SPA,선매품,2014,2,4,중가,40025560,2014_4
14007353,15999,A,5296549,의류/이미용,의류,캐주얼,영 캐릭터,선매품,2015,4,4,중가,40000500,2015_4
11364627,15999,A,2441370,의류/이미용,의류,캐주얼,영 트렌디,선매품,2014,2,3,중가,40000500,2014_3
12688251,15999,A,5336168,의류/이미용,의류,캐주얼,영 캐릭터,선매품,2015,4,4,중가,40000000,2015_4
6934165,15999,A,4357597,의류/이미용,의류,캐주얼,영 캐릭터,선매품,2015,3,2,중가,40000000,2015_2
15519746,15999,A,5165907,의류/이미용,의류,캐주얼,영 캐릭터,선매품,2015,4,3,중가,40000000,2015_3
16994683,15999,A,4357796,의류/이미용,의류,캐주얼,영 캐릭터,선매품,2015,3,2,중가,40000000,2015_2

*** 침구/주방

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
16389367,13737,A,5572033,침구/주방,주방,주방가전,김치냉장고,선매품,2015,4,4,고가,24987200,2015_4
4803308,97,A,1808542,침구/주방,주방,식기,수입도자기,일용품,2014,1,2,고가,15895000,2014_2
15380841,3472,A,4958112,침구/주방,주방,주방가전,에어컨,선매품,2015,4,3,고가,13832200,2015_3
6557744,8188,A,4321820,침구/주방,주방,주방가전,에어컨,선매품,2015,3,2,고가,11523600,2015_2
1962466,508,A,1375295,침구/주방,주방,주방용품,수입주방,일용품,2014,1,1,중가,10735000,2014_1
12528708,3678,A,5556256,침구/주방,주방,주방용품,수입주방,일용품,2015,4,4,중가,10602000,2015_4
16137551,3514,A,4799305,침구/주방,주방,주방가전,에어컨,선매품,2015,4,3,고가,10306530,2015_3
9694388,97,A,4133986,침구/주방,주방,식기,수입도자기,일용품,2015,3,2,고가,10283000,2015_2
9678821,11745,A,1400375,침구/주방,주방,주방가전,건강가전,선매품,2014,1,1,고가,10148000,2014_1
20033895,316,A,4975900,침구/주방,주방,주방가전,건강가전,선매품,2015,4,3,고가,10088000,2015_3
1943481,97,A,1548858,침구/주방,주방,주방가전,에어컨,선매품,2014,1,1,고가,10010400,2014_1
2011302,313,A,1427464,침구/주방,주방,주방가전,건강가전,선매품,2014,1,1,고가,10000700,2014_1
7941996,2036,A,4500492,침구/주방,주방,주방가전,에어컨,선매품,2015,3,2,고가,10000000,2015_2
23572749,6762,A,5461372,침구/주방,주방,주방용품,주방잡화,일용품,2015,4,4,중가,10000000,2015_4
16869353,6431,A,2265758,침구/주방,주방,주방가전,에어컨,선매품,2014,2,3,고가,10000000,2014_3
10929977,7112,A,5464467,침구/주방,주방,주방가전,건강가전,선매품,2015,4,4,고가,9490500,2015_4
5054540,7112,A,5728075,침구/주방,주방,주방가전,건강가전,선매품,2015,4,4,고가,9490500,2015_4
13558943,14464,A,4743533,침구/주방,주방,식기,수입도자기,일용품,2015,4,3,고가,9330900,2015_3
18189448,4697,A,5732391,침구/주방,주방,주방가전,건강가전,선매품,2015,4,4,고가,8950000,2015_4
7300936,8569,A,3302350,침구/주방,주방,주방가전,건강가전,선매품,2014,2,4,고가,8681500,2014_4

*** 교육문화/아동

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
23147928,16382,A,5465875,교육문화/아동,아동,아동,N/B 아동복,일용품,2015,4,4,중가,10008000,2015_4
23147924,16382,A,5465871,교육문화/아동,아동,아동,N/B 아동복,일용품,2015,4,4,중가,10008000,2015_4
12233751,14639,B,10341613,교육문화/아동,교육문화,교육보조재,피아노,일용품,2015,3,1,중가,9150000,2015_1
6959466,8079,A,3661993,교육문화/아동,아동,아동,N/B 아동복,일용품,2015,3,1,중가,7233840,2015_1
13694938,7982,A,3773484,교육문화/아동,아동,아동,수입 아동복,일용품,2015,3,1,중가,7015500,2015_1
6584812,9518,A,1864956,교육문화/아동,아동,아동,유아복,일용품,2014,1,2,중가,6698000,2014_2
16920924,19285,A,4036008,교육문화/아동,아동,아동,수입 아동복,일용품,2015,3,2,중가,5535000,2015_2
7370467,13296,A,5259819,교육문화/아동,아동,아동,수입 아동복,일용품,2015,4,4,중가,5280000,2015_4
15431129,16382,A,4062347,교육문화/아동,아동,아동,N/B 아동복,일용품,2015,3,2,중가,5266800,2015_2
17081069,9039,A,5399709,교육문화/아동,아동,아동,N/B 아동복,일용품,2015,4,4,중가,5096340,2015_4
11154408,7260,A,3116844,교육문화/아동,아동,아동,N/B 아동복,일용품,2014,2,4,중가,5069430,2014_4
22690409,15615,A,3657318,교육문화/아동,아동,아동,N/B 아동복,일용품,2015,3,1,중가,5040000,2015_1
797901,15615,A,1173383,교육문화/아동,아동,아동,N/B 아동복,일용품,2014,1,1,중가,5004000,2014_1
14048590,19285,A,5130978,교육문화/아동,아동,아동,수입 아동복,일용품,2015,4,3,중가,5000000,2015_3
9381596,6221,A,4717947,교육문화/아동,아동,아동,수입 아동복,일용품,2015,4,3,중가,5000000,2015_3
12198942,19285,A,5453441,교육문화/아동,아동,아동,수입 아동복,일용품,2015,4,4,중가,5000000,2015_4
13919276,6221,A,4762045,교육문화/아동,아동,아동,수입 아동복,일용품,2015,4,3,중가,5000000,2015_3
18884637,15261,B,9444759,교육문화/아동,아동,아동복합샵,카테고리킬러,일용품,2014,2,4,저가,4987200,2014_4
6584811,9518,A,1864955,교육문화/아동,아동,아동,유아복,일용품,2014,1,2,중가,4936000,2014_2
5490298,9518,A,1864853,교육문화/아동,아동,아동,유아복,일용품,2014,1,2,중가,4936000,2014_2

*** 가구인테리어/잡화

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
11329579,14323,A,1416069,가구인테리어/잡화,잡화,명품,명품잡화,사치품,2014,1,1,고가,101330000,2014_1
6562471,14323,A,1500785,가구인테리어/잡화,잡화,명품,명품잡화,사치품,2014,1,1,고가,101110000,2014_1
15406110,14323,A,1677262,가구인테리어/잡화,잡화,명품,명품잡화,사치품,2014,1,2,고가,99960000,2014_2
18057381,13376,A,4593637,가구인테리어/잡화,잡화,명품,디자이너,사치품,2015,3,2,고가,87769260,2015_2
23570287,2290,A,4573361,가구인테리어/잡화,잡화,명품,명품잡화보석,사치품,2015,3,2,고가,74410000,2015_2
23570286,2290,A,4573360,가구인테리어/잡화,잡화,명품,명품잡화보석,사치품,2015,3,2,고가,74410000,2015_2
27416874,14323,A,1862939,가구인테리어/잡화,잡화,명품,명품잡화,사치품,2014,1,2,고가,72915000,2014_2
10956725,13376,A,4391202,가구인테리어/잡화,잡화,명품,컨템포러리,사치품,2015,3,2,고가,71042900,2015_2
12678904,7982,A,3753522,가구인테리어/잡화,잡화,명품,수입의류,사치품,2015,3,1,고가,68215680,2015_1
21417431,6673,A,3946217,가구인테리어/잡화,잡화,명품,명품보석,사치품,2015,3,1,고가,68000000,2015_1
8534455,610,A,2797174,가구인테리어/잡화,잡화,명품,명품시계기타,사치품,2014,2,3,고가,67780000,2014_3
19756437,6236,A,2304352,가구인테리어/잡화,잡화,명품,명품시계기타,사치품,2014,2,3,고가,66000000,2014_3
6708236,610,A,2748405,가구인테리어/잡화,잡화,명품,명품시계기타,사치품,2014,2,3,고가,64780000,2014_3
3895710,1334,A,3581196,가구인테리어/잡화,잡화,명품,명품잡화보석,사치품,2015,3,1,고가,61640000,2015_1
13268896,1945,A,2743068,가구인테리어/잡화,잡화,명품,명품시계기타,사치품,2014,2,3,고가,56388200,2014_3
3757939,6454,A,1229794,가구인테리어/잡화,잡화,준보석/시계,시계,사치품,2014,1,1,고가,55000000,2014_1
27966506,13376,A,5706536,가구인테리어/잡화,잡화,명품,수입의류,사치품,2015,4,4,고가,54817500,2015_4
9348782,4659,A,5045943,가구인테리어/잡화,잡화,피혁잡화,Bag&Bag,선매품,2015,4,3,중가,54264000,2015_3
22862012,314,A,5237267,가구인테리어/잡화,잡화,보석,보석,사치품,2015,4,4,고가,53550000,2015_4
27581680,1268,A,5394053,가구인테리어/잡화,잡화,보석,보석,사치품,2015,4,4,고가,52125000,2015_4

*** 가전/레저취미/멀티샵

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
9493602,5814,A,5759315,가전/레저취미/멀티샵,레저취미,스포츠,스포츠의류,선매품,2015,4,4,중가,42065280,2015_4
2093875,4369,A,1728978,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,2,중가,37800000,2014_2
10447502,7926,A,3614648,가전/레저취미/멀티샵,가전,전자/전기,명품오디오,선매품,2015,3,1,고가,34500000,2015_1
3725509,7862,A,1450469,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,1,중가,30974140,2014_1
3725510,7862,A,1450470,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,1,중가,26413920,2014_1
10139498,8079,A,5704696,가전/레저취미/멀티샵,레저취미,스포츠,머렐,선매품,2015,4,4,중가,25000020,2015_4
27757411,3457,A,3769884,가전/레저취미/멀티샵,가전,전자/전기,명품오디오,선매품,2015,3,1,고가,25000000,2015_1
9673793,4369,A,4123627,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2015,3,2,중가,23000000,2015_2
4094101,7862,A,2207877,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,2,중가,22163090,2014_2
2602629,8079,A,2094877,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,2,중가,21960000,2014_2
6160331,1458,A,3645751,가전/레저취미/멀티샵,가전,전자/전기,명품오디오,선매품,2015,3,1,고가,21050000,2015_1
6849025,8079,A,1791170,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,2,중가,20700000,2014_2
5542428,9689,A,3380392,가전/레저취미/멀티샵,레저취미,스포츠,스포츠의류,선매품,2014,2,4,중가,20430630,2014_4
21482051,12446,A,5331011,가전/레저취미/멀티샵,레저취미,골프용품,우리골프,사치품,2015,4,4,고가,20000000,2015_4
20500094,14830,A,3156156,가전/레저취미/멀티샵,레저취미,골프용품,골프용품,사치품,2014,2,4,고가,20000000,2014_4
10678213,3452,A,5047468,가전/레저취미/멀티샵,가전,전자/전기,명품오디오,선매품,2015,4,3,고가,18700000,2015_3
15652503,3452,A,5031371,가전/레저취미/멀티샵,가전,전자/전기,명품오디오,선매품,2015,4,3,고가,18400000,2015_3
2298299,8156,A,1245543,가전/레저취미/멀티샵,가전,전자/전기,명품오디오,선매품,2014,1,1,고가,18107000,2014_1
9707446,8079,A,2028921,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,2,중가,18000000,2014_2
2679865,8079,A,2090503,가전/레저취미/멀티샵,레저취미,스포츠,L/C 아웃도어,선매품,2014,1,2,중가,18000000,2014_2

In [95]:
pd.pivot_table(data = purchase_real,
             index = ['BBCL', 'PURYEAR','PRICE_TYPE'],
             values = 'PURAMT',
             aggfunc = ['max','median','min','count','mean','sum'])

                                      max  median    min    count  \
                                   PURAMT  PURAMT PURAMT   PURAMT
BBCL        PURYEAR PRICE_TYPE
가구인테리어/잡화   2014    고가          101330000  394200    200    39959
                    저가           12000000    8200     10   315296
                    중가           43014510  117000     10    80583
            2015    고가           87769260  396000    100    47623
                    저가           10000460    7900      2   292431
                    중가           54264000  116420    100    80381
가전/레저취미/멀티샵 2014    고가           20000000  171925    100    39184
                    저가            4000000    8000     10    86467
                    중가           37800000   79000     30   122238
            2015    고가           34500000  175000    100    39649
                    저가            4800000    6990     10    89395
                    중가           42065280   76000     40   122520
교육문화/아동     2014    고가            2880000   27000    310    15303
                    저가            4987200    3500     10    99292
                    중가            6698000   27100    100   170387
            2015    고가            3763000   28000    400    26013
                    저가            1323000    3350     10    95336
                    중가           10008000   27360     10   166275
식품/생활       2014    고가           51098000   13300     11   714305
                    저가            7200000    1990     10  4172114
                    중가           23976000    5000      6  6748050
            2015    고가           93654000   13965     10   759001
                    저가            4860000    2000     10  4714542
                    중가           16231270    5000     10  7059937
의류/이미용      2014    고가           82800000   72200    100   180572
                    저가           12311000    9900     10   360922
                    중가           53320700   77700     10   400864
            2015    고가           46796400   74100     50   180365
                    저가            8731200    9900      1   402722
                    중가           93166350   79000     10   393125
침구/주방       2014    고가           15895000   62100    100    60453
                    저가            1400000    3500     10   212473
                    중가           10735000   30000    100    53052
            2015    고가           24987200   64000     70    60092
                    저가            1184000    3950    100   134296
                    중가           10602000   29700    100    57813

                                         mean          sum
                                       PURAMT       PURAMT
BBCL        PURYEAR PRICE_TYPE
가구인테리어/잡화   2014    고가          962066.362021  38443209760
                    저가           18222.756350   5745562186
                    중가          177534.308849  14306247210
            2015    고가          984640.525586  46891535750
                    저가           19155.260263   5601591914
                    중가          166819.462062  13409115180
가전/레저취미/멀티샵 2014    고가          423164.165986  16581264680
                    저가           18591.467265   1607548400
                    중가          136202.535218  16649125500
            2015    고가          453958.294282  17998992410
                    저가           15749.619386   1407937225
                    중가          131653.391691  16130173550
교육문화/아동     2014    고가           42257.854016    646671940
                    저가            9418.090168    935141009
                    중가           59063.423248  10063639497
            2015    고가           42341.959366   1101441389
                    저가            9126.857147    870118053
                    중가           60596.050489  10075608295
식품/생활       2014    고가           38174.988197  27268584944
                    저가            2799.569524  11680123205
                    중가            8286.124581  55915182981
            2015    고가           38668.850647  29349696310
                    저가            2781.733622  13114599996
                    중가            8053.378849  56856347312
의류/이미용      2014    고가          182852.235341  33017993840
                    저가           19955.513579   7202383872
                    중가          185981.655571  74553350379
            2015    고가          182555.128545  32926555760
                    저가           19544.232617   7870892448
                    중가          199800.928763  78546740120
침구/주방       2014    고가          168233.996989  10170249820
                    저가            6399.357504   1359690687
                    중가           65141.194884   3455870671
            2015    고가          176912.580543  10631030790
                    저가            7137.570240    958547133
                    중가           63591.107969   3676392725

## 함수 생성

In [68]:
def pivot(df, aggfunc):
    # 분기 변경
    df['Q_year'] = df['PURYEAR'].astype(str)+ '_' + df['QUARTER'].astype(str)
    df['Q_year']

    # 년도
    pivot_df_year = pd.pivot_table(df,
                             values = 'PURAMT',
                             index = 'CUSTNO',
                             columns = ['PURYEAR', 'BBCL', 'PRICE_TYPE'],
                             aggfunc = aggfunc)
    pivot_df_year.fillna(0, inplace = True)
    columns_name = []
    for indexs in pivot_df_year.columns:
         columns_name.append('_'.join([aggfunc] + [str(idx) for idx in indexs]))
    pivot_df_year.columns = columns_name
    
    # 년도 총액
    pivot_df_label_year = pd.pivot_table(df,
                                        values = 'PURAMT',
                                        index = 'CUSTNO',
                                        columns = ['PURYEAR'],
                                        aggfunc = 'sum')
    pivot_df_label_year.fillna(0, inplace = True)
    
    # 반기
    pivot_df_half = pd.pivot_table(df,
                                     values = 'PURAMT',
                                     index = 'CUSTNO',
                                     columns = ['HALF_YEAR', 'BBCL', 'PRICE_TYPE'],
                                     aggfunc = aggfunc) # 대분류하는것
    pivot_df_half.fillna(0, inplace = True)
    # 컬럼 변경
    columns_name = []
    for indexs in pivot_df_half.columns:
         columns_name.append('_'.join([aggfunc, '반기'] + [str(idx) for idx in indexs]))
    pivot_df_half.columns = columns_name
    
    # 반기 총액
    pivot_df_label_half = pd.pivot_table(df,
                                        values = 'PURAMT',
                                        index = 'CUSTNO',
                                        columns = ['HALF_YEAR'],
                                        aggfunc = 'sum')
    pivot_df_label_half.fillna(0, inplace = True)
    
    # 분기
    pivot_df_q_ = pd.pivot_table(df,
                               values = 'PURAMT',
                               index = 'CUSTNO',
                               columns = ['Q_year', 'BBCL', 'PRICE_TYPE'],
                               aggfunc = aggfunc)
    pivot_df_q_.fillna(0, inplace = True)
    # 컬럼 변경
    columns_name = []
    for indexs in pivot_df_q_.columns:
         columns_name.append('_'.join([aggfunc, '분기'] + [str(idx) for idx in indexs]))
    pivot_df_q_.columns = columns_name
    
    # 분기 총액
    pivot_df_label_q = pd.pivot_table(df,
                                values = 'PURAMT',
                                index = 'CUSTNO',
                                columns = ['Q_year'],
                                aggfunc = 'sum')
    pivot_df_label_q.fillna(0, inplace = True)
    
    pivot_total_ = pd.concat([pivot_df_year, pivot_df_half, pivot_df_q_], axis = 1)
    
    def minus(x):
        if x > 0: y = 1
        else: y = 0
        return y
  
    # 년도기준 증가
    pivot_total_['year_up'] = pivot_df_label_year[2015] -  pivot_df_label_year[2014]
    pivot_total_['year_label'] = pivot_total_['year_up'].apply(lambda x : minus(x))
    # 반기기준 증가
    pivot_total_['half_up'] = pivot_df_label_half[4] -  pivot_df_label_half[1]
    pivot_total_['half_label'] = pivot_total_['half_up'].apply(lambda x : minus(x))
    # 분기기준 증가
    pivot_total_['q_up'] = pivot_df_label_q['2015_4'] -  pivot_df_label_q['2014_1']
    pivot_total_['q_label'] = pivot_total_['q_up'].apply(lambda x : minus(x))
    
    total_df = pivot_total_.copy()
    return total_df

## 함수 대입

### count

In [69]:
purchase_pviot_cnt = pivot(purchase_real, 'count')
purchase_pviot_cnt

,count_2014_가구인테리어/잡화_고가,count_2014_가구인테리어/잡화_저가,count_2014_가구인테리어/잡화_중가,count_2014_가전/레저취미/멀티샵_고가,count_2014_가전/레저취미/멀티샵_저가,count_2014_가전/레저취미/멀티샵_중가,count_2014_교육문화/아동_고가,count_2014_교육문화/아동_저가,count_2014_교육문화/아동_중가,count_2014_식품/생활_고가,...,count_분기_2015_4_의류/이미용_중가,count_분기_2015_4_침구/주방_고가,count_분기_2015_4_침구/주방_저가,count_분기_2015_4_침구/주방_중가,year_up,year_label,half_up,half_label,q_up,q_label
CUSTNO,,,,,,,,,,,,,,,,,,,,,
1,1.0,23.0,11.0,13.0,0.0,3.0,0.0,0.0,2.0,49.0,...,17.0,2.0,0.0,1.0,-23040784.0,0,-6822837.0,0,-3845652.0,0
2,1.0,51.0,3.0,17.0,3.0,2.0,0.0,0.0,4.0,46.0,...,8.0,0.0,0.0,3.0,7390100.0,1,1520590.0,1,-2122250.0,0
3,0.0,89.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,-622371.0,0,-172097.0,0,-44681.0,0
4,0.0,21.0,4.0,4.0,1.0,4.0,0.0,0.0,0.0,9.0,...,8.0,0.0,0.0,2.0,-1905422.0,0,-1304849.0,0,300502.0,1
5,1.0,34.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,47.0,...,2.0,0.0,0.0,0.0,-2134690.0,0,-2843890.0,0,-529070.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19379,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,0.0,0.0,0.0,3398040.0,1,2192740.0,1,1387190.0,1
19380,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,9.0,0.0,0.0,0.0,2867577.0,1,2552327.0,1,2183420.0,1
19381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,12.0,1.0,6040669.0,1,3243498.0,1,1375997.0,1
19382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,1.0,4401773.0,1,2575034.0,1,1308847.0,1
19383,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,0.0,0.0,0.0,2384400.0,1,2357400.0,1,1265040.0,1

In [70]:
purchase_pviot_cnt.columns.tolist()

['count_2014_가구인테리어/잡화_고가',
 'count_2014_가구인테리어/잡화_저가',
 'count_2014_가구인테리어/잡화_중가',
 'count_2014_가전/레저취미/멀티샵_고가',
 'count_2014_가전/레저취미/멀티샵_저가',
 'count_2014_가전/레저취미/멀티샵_중가',
 'count_2014_교육문화/아동_고가',
 'count_2014_교육문화/아동_저가',
 'count_2014_교육문화/아동_중가',
 'count_2014_식품/생활_고가',
 'count_2014_식품/생활_저가',
 'count_2014_식품/생활_중가',
 'count_2014_의류/이미용_고가',
 'count_2014_의류/이미용_저가',
 'count_2014_의류/이미용_중가',
 'count_2014_침구/주방_고가',
 'count_2014_침구/주방_저가',
 'count_2014_침구/주방_중가',
 'count_2015_가구인테리어/잡화_고가',
 'count_2015_가구인테리어/잡화_저가',
 'count_2015_가구인테리어/잡화_중가',
 'count_2015_가전/레저취미/멀티샵_고가',
 'count_2015_가전/레저취미/멀티샵_저가',
 'count_2015_가전/레저취미/멀티샵_중가',
 'count_2015_교육문화/아동_고가',
 'count_2015_교육문화/아동_저가',
 'count_2015_교육문화/아동_중가',
 'count_2015_식품/생활_고가',
 'count_2015_식품/생활_저가',
 'count_2015_식품/생활_중가',
 'count_2015_의류/이미용_고가',
 'count_2015_의류/이미용_저가',
 'count_2015_의류/이미용_중가',
 'count_2015_침구/주방_고가',
 'count_2015_침구/주방_저가',
 'count_2015_침구/주방_중가',
 'count_반기_1_가구인테리어/잡화_고가',
 'count_반기_1_가구인테리어/잡화_저가',
 'count_반기_1_가구인테리어/잡화_중가',
 'count_반기_1_가전/레저취미/멀티샵_고가',
 'count_반기_1_가전/레저취미/멀티샵_저가',
 'count_반기_1_가전/레저취미/멀티샵_중가',
 'count_반기_1_교육문화/아동_고가',
 'count_반기_1_교육문화/아동_저가',
 'count_반기_1_교육문화/아동_중가',
 'count_반기_1_식품/생활_고가',
 'count_반기_1_식품/생활_저가',
 'count_반기_1_식품/생활_중가',
 'count_반기_1_의류/이미용_고가',
 'count_반기_1_의류/이미용_저가',
 'count_반기_1_의류/이미용_중가',
 'count_반기_1_침구/주방_고가',
 'count_반기_1_침구/주방_저가',
 'count_반기_1_침구/주방_중가',
 'count_반기_2_가구인테리어/잡화_고가',
 'count_반기_2_가구인테리어/잡화_저가',
 'count_반기_2_가구인테리어/잡화_중가',
 'count_반기_2_가전/레저취미/멀티샵_고가',
 'count_반기_2_가전/레저취미/멀티샵_저가',
 'count_반기_2_가전/레저취미/멀티샵_중가',
 'count_반기_2_교육문화/아동_고가',
 'count_반기_2_교육문화/아동_저가',
 'count_반기_2_교육문화/아동_중가',
 'count_반기_2_식품/생활_고가',
 'count_반기_2_식품/생활_저가',
 'count_반기_2_식품/생활_중가',
 'count_반기_2_의류/이미용_고가',
 'count_반기_2_의류/이미용_저가',
 'count_반기_2_의류/이미용_중가',
 'count_반기_2_침구/주방_고가',
 'count_반기_2_침구/주방_저가',
 'count_반기_2_침구/주방_중가',
 'count_반기_3_가구인테리어/잡화_고가',
 'count_반기_3_가구인테리어/잡화_저가',
 'count_반기_3_가구인테리어/잡화_중가',
 'count_반기_3_가전/레저취미/멀티샵_고가',
 'count_반기_3_가전/레저취미/멀티샵_저가',
 'count_반기_3_가전/레저취미/멀티샵_중가',
 'count_반기_3_교육문화/아동_고가',
 'count_반기_3_교육문화/아동_저가',
 'count_반기_3_교육문화/아동_중가',
 'count_반기_3_식품/생활_고가',
 'count_반기_3_식품/생활_저가',
 'count_반기_3_식품/생활_중가',
 'count_반기_3_의류/이미용_고가',
 'count_반기_3_의류/이미용_저가',
 'count_반기_3_의류/이미용_중가',
 'count_반기_3_침구/주방_고가',
 'count_반기_3_침구/주방_저가',
 'count_반기_3_침구/주방_중가',
 'count_반기_4_가구인테리어/잡화_고가',
 'count_반기_4_가구인테리어/잡화_저가',
 'count_반기_4_가구인테리어/잡화_중가',
 'count_반기_4_가전/레저취미/멀티샵_고가',
 'count_반기_4_가전/레저취미/멀티샵_저가',
 'count_반기_4_가전/레저취미/멀티샵_중가',
 'count_반기_4_교육문화/아동_고가',
 'count_반기_4_교육문화/아동_저가',
 'count_반기_4_교육문화/아동_중가',
 'count_반기_4_식품/생활_고가',
 'count_반기_4_식품/생활_저가',
 'count_반기_4_식품/생활_중가',
 'count_반기_4_의류/이미용_고가',
 'count_반기_4_의류/이미용_저가',
 'count_반기_4_의류/이미용_중가',
 'count_반기_4_침구/주방_고가',
 'count_반기_4_침구/주방_저가',
 'count_반기_4_침구/주방_중가',
 'count_분기_2014_1_가구인테리어/잡화_고가',
 'count_분기_2014_1_가구인테리어/잡화_저가',
 'count_분기_2014_1_가구인테리어/잡화_중가',
 'count_분기_2014_1_가전/레저취미/멀티샵_고가',
 'count_분기_2014_1_가전/레저취미/멀티샵_저가',
 'count_분기_2014_1_가전/레저취미/멀티샵_중가',
 'count_분기_2014_1_교육문화/아동_고가',
 'count_분기_2014_1_교육문화/아동_저가',
 'count_분기_2014_1_교육문화/아동_중가',
 'count_분기_2014_1_식품/생활_고가',
 'count_분기_2014_1_식품/생활_저가',
 'count_분기_2014_1_식품/생활_중가',
 'count_분기_2014_1_의류/이미용_고가',
 'count_분기_2014_1_의류/이미용_저가',
 'count_분기_2014_1_의류/이미용_중가',
 'count_분기_2014_1_침구/주방_고가',
 'count_분기_2014_1_침구/주방_저가',
 'count_분기_2014_1_침구/주방_중가',
 'count_분기_2014_2_가구인테리어/잡화_고가',
 'count_분기_2014_2_가구인테리어/잡화_저가',
 'count_분기_2014_2_가구인테리어/잡화_중가',
 'count_분기_2014_2_가전/레저취미/멀티샵_고가',
 'count_분기_2014_2_가전/레저취미/멀티샵_저가',
 'count_분기_2014_2_가전/레저취미/멀티샵_중가',
 'count_분기_2014_2_교육문화/아동_고가',
 'count_분기_2014_2_교육문화/아동_저가',
 'count_분기_2014_2_교육문화/아동_중가',
 'count_분기_2014_2_식품/생활_고가',
 'count_분기_2014_2_식품/생활_저가',
 'count_분기_2014_2_식품/생활_중가',
 'count_분기_2014_2_의류/이미용_고가',
 'count_분기_2014_2_의류/이미용_저가',
 'count_분기_2014_2_의류/이미용_중가',
 'count_분기_2014_2_침구/주방_고가',
 'count_분기_2014_2_침구/주방_저가',
 'count_분기_2014_2_침구/주방_중가',
 'count_분기_2014_3_가구인테리어/잡화_고가',
 'count_분기_2014_3_가구인테리어/잡화_저가',
 'count_분기_2014_3_가구인테리어/잡화_중가',
 'count_분기_2014_3_가전/레저취미/멀티샵_고가',
 'count_분기_2014_3_가전/레저취미/멀티샵_저가',
 'count_분기_2014_3_가전/레저취미/멀티샵_중가',
 'count_분기_2014_3_교육문화/아동_고가',
 'count_분기_2014_3_교육문화/아동_저가',
 'count_분기_2014_3_교육문화/아동_중가',
 'count_분기_2014_3_식품/생활_고가',
 'count_분기_2014_3_식품/생활_저가',
 'count_분기_2014_3_식품/생활_중가',
 'count_분기_2014_3_의류/이미용_고가',
 'count_분기_2014_3_의류/이미용_저가',
 'count_분기_2014_3_의류/이미용_중가',
 'count_분기_2014_3_침구/주방_고가',
 'count_분기_2014_3_침구/주방_저가',
 'count_분기_2014_3_침구/주방_중가',
 'count_분기_2014_4_가구인테리어/잡화_고가',
 'count_분기_2014_4_가구인테리어/잡화_저가',
 'count_분기_2014_4_가구인테리어/잡화_중가',
 'count_분기_2014_4_가전/레저취미/멀티샵_고가',
 'count_분기_2014_4_가전/레저취미/멀티샵_저가',
 'count_분기_2014_4_가전/레저취미/멀티샵_중가',
 'count_분기_2014_4_교육문화/아동_고가',
 'count_분기_2014_4_교육문화/아동_저가',
 'count_분기_2014_4_교육문화/아동_중가',
 'count_분기_2014_4_식품/생활_고가',
 'count_분기_2014_4_식품/생활_저가',
 'count_분기_2014_4_식품/생활_중가',
 'count_분기_2014_4_의류/이미용_고가',
 'count_분기_2014_4_의류/이미용_저가',
 'count_분기_2014_4_의류/이미용_중가',
 'count_분기_2014_4_침구/주방_고가',
 'count_분기_2014_4_침구/주방_저가',
 'count_분기_2014_4_침구/주방_중가',
 'count_분기_2015_1_가구인테리어/잡화_고가',
 'count_분기_2015_1_가구인테리어/잡화_저가',
 'count_분기_2015_1_가구인테리어/잡화_중가',
 'count_분기_2015_1_가전/레저취미/멀티샵_고가',
 'count_분기_2015_1_가전/레저취미/멀티샵_저가',
 'count_분기_2015_1_가전/레저취미/멀티샵_중가',
 'count_분기_2015_1_교육문화/아동_고가',
 'count_분기_2015_1_교육문화/아동_저가',
 'count_분기_2015_1_교육문화/아동_중가',
 'count_분기_2015_1_식품/생활_고가',
 'count_분기_2015_1_식품/생활_저가',
 'count_분기_2015_1_식품/생활_중가',
 'count_분기_2015_1_의류/이미용_고가',
 'count_분기_2015_1_의류/이미용_저가',
 'count_분기_2015_1_의류/이미용_중가',
 'count_분기_2015_1_침구/주방_고가',
 'count_분기_2015_1_침구/주방_저가',
 'count_분기_2015_1_침구/주방_중가',
 'count_분기_2015_2_가구인테리어/잡화_고가',
 'count_분기_2015_2_가구인테리어/잡화_저가',
 'count_분기_2015_2_가구인테리어/잡화_중가',
 'count_분기_2015_2_가전/레저취미/멀티샵_고가',
 'count_분기_2015_2_가전/레저취미/멀티샵_저가',
 'count_분기_2015_2_가전/레저취미/멀티샵_중가',
 'count_분기_2015_2_교육문화/아동_고가',
 'count_분기_2015_2_교육문화/아동_저가',
 'count_분기_2015_2_교육문화/아동_중가',
 'count_분기_2015_2_식품/생활_고가',
 'count_분기_2015_2_식품/생활_저가',
 'count_분기_2015_2_식품/생활_중가',
 'count_분기_2015_2_의류/이미용_고가',
 'count_분기_2015_2_의류/이미용_저가',
 'count_분기_2015_2_의류/이미용_중가',
 'count_분기_2015_2_침구/주방_고가',
 'count_분기_2015_2_침구/주방_저가',
 'count_분기_2015_2_침구/주방_중가',
 'count_분기_2015_3_가구인테리어/잡화_고가',
 'count_분기_2015_3_가구인테리어/잡화_저가',
 'count_분기_2015_3_가구인테리어/잡화_중가',
 'count_분기_2015_3_가전/레저취미/멀티샵_고가',
 'count_분기_2015_3_가전/레저취미/멀티샵_저가',
 'count_분기_2015_3_가전/레저취미/멀티샵_중가',
 'count_분기_2015_3_교육문화/아동_고가',
 'count_분기_2015_3_교육문화/아동_저가',
 'count_분기_2015_3_교육문화/아동_중가',
 'count_분기_2015_3_식품/생활_고가',
 'count_분기_2015_3_식품/생활_저가',
 'count_분기_2015_3_식품/생활_중가',
 'count_분기_2015_3_의류/이미용_고가',
 'count_분기_2015_3_의류/이미용_저가',
 'count_분기_2015_3_의류/이미용_중가',
 'count_분기_2015_3_침구/주방_고가',
 'count_분기_2015_3_침구/주방_저가',
 'count_분기_2015_3_침구/주방_중가',
 'count_분기_2015_4_가구인테리어/잡화_고가',
 'count_분기_2015_4_가구인테리어/잡화_저가',
 'count_분기_2015_4_가구인테리어/잡화_중가',
 'count_분기_2015_4_가전/레저취미/멀티샵_고가',
 'count_분기_2015_4_가전/레저취미/멀티샵_저가',
 'count_분기_2015_4_가전/레저취미/멀티샵_중가',
 'count_분기_2015_4_교육문화/아동_고가',
 'count_분기_2015_4_교육문화/아동_저가',
 'count_분기_2015_4_교육문화/아동_중가',
 'count_분기_2015_4_식품/생활_고가',
 'count_분기_2015_4_식품/생활_저가',
 'count_분기_2015_4_식품/생활_중가',
 'count_분기_2015_4_의류/이미용_고가',
 'count_분기_2015_4_의류/이미용_저가',
 'count_분기_2015_4_의류/이미용_중가',
 'count_분기_2015_4_침구/주방_고가',
 'count_분기_2015_4_침구/주방_저가',
 'count_분기_2015_4_침구/주방_중가',
 'year_up',
 'year_label',
 'half_up',
 'half_label',
 'q_up',
 'q_label']

### sum

In [71]:
purchase_pviot_sum = pivot(purchase_real, 'sum')
purchase_pviot_sum

,sum_2014_가구인테리어/잡화_고가,sum_2014_가구인테리어/잡화_저가,sum_2014_가구인테리어/잡화_중가,sum_2014_가전/레저취미/멀티샵_고가,sum_2014_가전/레저취미/멀티샵_저가,sum_2014_가전/레저취미/멀티샵_중가,sum_2014_교육문화/아동_고가,sum_2014_교육문화/아동_저가,sum_2014_교육문화/아동_중가,sum_2014_식품/생활_고가,...,sum_분기_2015_4_의류/이미용_중가,sum_분기_2015_4_침구/주방_고가,sum_분기_2015_4_침구/주방_저가,sum_분기_2015_4_침구/주방_중가,year_up,year_label,half_up,half_label,q_up,q_label
CUSTNO,,,,,,,,,,,,,,,,,,,,,
1,236550.0,1848200.0,1366400.0,8791650.0,0.0,130450.0,0.0,0.0,177460.0,4167867.0,...,3415160.0,137750.0,0.0,699200.0,-23040784.0,0,-6822837.0,0,-3845652.0,0
2,434150.0,1970530.0,461690.0,6410030.0,60500.0,244650.0,0.0,0.0,577050.0,1690010.0,...,3002000.0,0.0,0.0,432490.0,7390100.0,1,1520590.0,1,-2122250.0,0
3,0.0,9950.0,0.0,0.0,26900.0,0.0,0.0,0.0,0.0,121170.0,...,0.0,0.0,0.0,0.0,-622371.0,0,-172097.0,0,-44681.0,0
4,0.0,633710.0,520520.0,447350.0,5200.0,568100.0,0.0,0.0,0.0,106164.0,...,565980.0,0.0,0.0,54000.0,-1905422.0,0,-1304849.0,0,300502.0,1
5,57000.0,515380.0,197570.0,49900.0,0.0,134280.0,0.0,0.0,74200.0,1265640.0,...,717050.0,0.0,0.0,0.0,-2134690.0,0,-2843890.0,0,-529070.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19379,0.0,3150.0,449900.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,346780.0,0.0,0.0,0.0,3398040.0,1,2192740.0,1,1387190.0,1
19380,0.0,3000.0,0.0,0.0,9900.0,0.0,0.0,0.0,0.0,0.0,...,574000.0,0.0,0.0,0.0,2867577.0,1,2552327.0,1,2183420.0,1
19381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,78200.0,31600.0,6040669.0,1,3243498.0,1,1375997.0,1
19382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,12670.0,2900.0,4401773.0,1,2575034.0,1,1308847.0,1
19383,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,467900.0,0.0,0.0,0.0,2384400.0,1,2357400.0,1,1265040.0,1

In [72]:
purchase_pviot_sum.columns.tolist()

['sum_2014_가구인테리어/잡화_고가',
 'sum_2014_가구인테리어/잡화_저가',
 'sum_2014_가구인테리어/잡화_중가',
 'sum_2014_가전/레저취미/멀티샵_고가',
 'sum_2014_가전/레저취미/멀티샵_저가',
 'sum_2014_가전/레저취미/멀티샵_중가',
 'sum_2014_교육문화/아동_고가',
 'sum_2014_교육문화/아동_저가',
 'sum_2014_교육문화/아동_중가',
 'sum_2014_식품/생활_고가',
 'sum_2014_식품/생활_저가',
 'sum_2014_식품/생활_중가',
 'sum_2014_의류/이미용_고가',
 'sum_2014_의류/이미용_저가',
 'sum_2014_의류/이미용_중가',
 'sum_2014_침구/주방_고가',
 'sum_2014_침구/주방_저가',
 'sum_2014_침구/주방_중가',
 'sum_2015_가구인테리어/잡화_고가',
 'sum_2015_가구인테리어/잡화_저가',
 'sum_2015_가구인테리어/잡화_중가',
 'sum_2015_가전/레저취미/멀티샵_고가',
 'sum_2015_가전/레저취미/멀티샵_저가',
 'sum_2015_가전/레저취미/멀티샵_중가',
 'sum_2015_교육문화/아동_고가',
 'sum_2015_교육문화/아동_저가',
 'sum_2015_교육문화/아동_중가',
 'sum_2015_식품/생활_고가',
 'sum_2015_식품/생활_저가',
 'sum_2015_식품/생활_중가',
 'sum_2015_의류/이미용_고가',
 'sum_2015_의류/이미용_저가',
 'sum_2015_의류/이미용_중가',
 'sum_2015_침구/주방_고가',
 'sum_2015_침구/주방_저가',
 'sum_2015_침구/주방_중가',
 'sum_반기_1_가구인테리어/잡화_고가',
 'sum_반기_1_가구인테리어/잡화_저가',
 'sum_반기_1_가구인테리어/잡화_중가',
 'sum_반기_1_가전/레저취미/멀티샵_고가',
 'sum_반기_1_가전/레저취미/멀티샵_저가',
 'sum_반기_1_가전/레저취미/멀티샵_중가',
 'sum_반기_1_교육문화/아동_고가',
 'sum_반기_1_교육문화/아동_저가',
 'sum_반기_1_교육문화/아동_중가',
 'sum_반기_1_식품/생활_고가',
 'sum_반기_1_식품/생활_저가',
 'sum_반기_1_식품/생활_중가',
 'sum_반기_1_의류/이미용_고가',
 'sum_반기_1_의류/이미용_저가',
 'sum_반기_1_의류/이미용_중가',
 'sum_반기_1_침구/주방_고가',
 'sum_반기_1_침구/주방_저가',
 'sum_반기_1_침구/주방_중가',
 'sum_반기_2_가구인테리어/잡화_고가',
 'sum_반기_2_가구인테리어/잡화_저가',
 'sum_반기_2_가구인테리어/잡화_중가',
 'sum_반기_2_가전/레저취미/멀티샵_고가',
 'sum_반기_2_가전/레저취미/멀티샵_저가',
 'sum_반기_2_가전/레저취미/멀티샵_중가',
 'sum_반기_2_교육문화/아동_고가',
 'sum_반기_2_교육문화/아동_저가',
 'sum_반기_2_교육문화/아동_중가',
 'sum_반기_2_식품/생활_고가',
 'sum_반기_2_식품/생활_저가',
 'sum_반기_2_식품/생활_중가',
 'sum_반기_2_의류/이미용_고가',
 'sum_반기_2_의류/이미용_저가',
 'sum_반기_2_의류/이미용_중가',
 'sum_반기_2_침구/주방_고가',
 'sum_반기_2_침구/주방_저가',
 'sum_반기_2_침구/주방_중가',
 'sum_반기_3_가구인테리어/잡화_고가',
 'sum_반기_3_가구인테리어/잡화_저가',
 'sum_반기_3_가구인테리어/잡화_중가',
 'sum_반기_3_가전/레저취미/멀티샵_고가',
 'sum_반기_3_가전/레저취미/멀티샵_저가',
 'sum_반기_3_가전/레저취미/멀티샵_중가',
 'sum_반기_3_교육문화/아동_고가',
 'sum_반기_3_교육문화/아동_저가',
 'sum_반기_3_교육문화/아동_중가',
 'sum_반기_3_식품/생활_고가',
 'sum_반기_3_식품/생활_저가',
 'sum_반기_3_식품/생활_중가',
 'sum_반기_3_의류/이미용_고가',
 'sum_반기_3_의류/이미용_저가',
 'sum_반기_3_의류/이미용_중가',
 'sum_반기_3_침구/주방_고가',
 'sum_반기_3_침구/주방_저가',
 'sum_반기_3_침구/주방_중가',
 'sum_반기_4_가구인테리어/잡화_고가',
 'sum_반기_4_가구인테리어/잡화_저가',
 'sum_반기_4_가구인테리어/잡화_중가',
 'sum_반기_4_가전/레저취미/멀티샵_고가',
 'sum_반기_4_가전/레저취미/멀티샵_저가',
 'sum_반기_4_가전/레저취미/멀티샵_중가',
 'sum_반기_4_교육문화/아동_고가',
 'sum_반기_4_교육문화/아동_저가',
 'sum_반기_4_교육문화/아동_중가',
 'sum_반기_4_식품/생활_고가',
 'sum_반기_4_식품/생활_저가',
 'sum_반기_4_식품/생활_중가',
 'sum_반기_4_의류/이미용_고가',
 'sum_반기_4_의류/이미용_저가',
 'sum_반기_4_의류/이미용_중가',
 'sum_반기_4_침구/주방_고가',
 'sum_반기_4_침구/주방_저가',
 'sum_반기_4_침구/주방_중가',
 'sum_분기_2014_1_가구인테리어/잡화_고가',
 'sum_분기_2014_1_가구인테리어/잡화_저가',
 'sum_분기_2014_1_가구인테리어/잡화_중가',
 'sum_분기_2014_1_가전/레저취미/멀티샵_고가',
 'sum_분기_2014_1_가전/레저취미/멀티샵_저가',
 'sum_분기_2014_1_가전/레저취미/멀티샵_중가',
 'sum_분기_2014_1_교육문화/아동_고가',
 'sum_분기_2014_1_교육문화/아동_저가',
 'sum_분기_2014_1_교육문화/아동_중가',
 'sum_분기_2014_1_식품/생활_고가',
 'sum_분기_2014_1_식품/생활_저가',
 'sum_분기_2014_1_식품/생활_중가',
 'sum_분기_2014_1_의류/이미용_고가',
 'sum_분기_2014_1_의류/이미용_저가',
 'sum_분기_2014_1_의류/이미용_중가',
 'sum_분기_2014_1_침구/주방_고가',
 'sum_분기_2014_1_침구/주방_저가',
 'sum_분기_2014_1_침구/주방_중가',
 'sum_분기_2014_2_가구인테리어/잡화_고가',
 'sum_분기_2014_2_가구인테리어/잡화_저가',
 'sum_분기_2014_2_가구인테리어/잡화_중가',
 'sum_분기_2014_2_가전/레저취미/멀티샵_고가',
 'sum_분기_2014_2_가전/레저취미/멀티샵_저가',
 'sum_분기_2014_2_가전/레저취미/멀티샵_중가',
 'sum_분기_2014_2_교육문화/아동_고가',
 'sum_분기_2014_2_교육문화/아동_저가',
 'sum_분기_2014_2_교육문화/아동_중가',
 'sum_분기_2014_2_식품/생활_고가',
 'sum_분기_2014_2_식품/생활_저가',
 'sum_분기_2014_2_식품/생활_중가',
 'sum_분기_2014_2_의류/이미용_고가',
 'sum_분기_2014_2_의류/이미용_저가',
 'sum_분기_2014_2_의류/이미용_중가',
 'sum_분기_2014_2_침구/주방_고가',
 'sum_분기_2014_2_침구/주방_저가',
 'sum_분기_2014_2_침구/주방_중가',
 'sum_분기_2014_3_가구인테리어/잡화_고가',
 'sum_분기_2014_3_가구인테리어/잡화_저가',
 'sum_분기_2014_3_가구인테리어/잡화_중가',
 'sum_분기_2014_3_가전/레저취미/멀티샵_고가',
 'sum_분기_2014_3_가전/레저취미/멀티샵_저가',
 'sum_분기_2014_3_가전/레저취미/멀티샵_중가',
 'sum_분기_2014_3_교육문화/아동_고가',
 'sum_분기_2014_3_교육문화/아동_저가',
 'sum_분기_2014_3_교육문화/아동_중가',
 'sum_분기_2014_3_식품/생활_고가',
 'sum_분기_2014_3_식품/생활_저가',
 'sum_분기_2014_3_식품/생활_중가',
 'sum_분기_2014_3_의류/이미용_고가',
 'sum_분기_2014_3_의류/이미용_저가',
 'sum_분기_2014_3_의류/이미용_중가',
 'sum_분기_2014_3_침구/주방_고가',
 'sum_분기_2014_3_침구/주방_저가',
 'sum_분기_2014_3_침구/주방_중가',
 'sum_분기_2014_4_가구인테리어/잡화_고가',
 'sum_분기_2014_4_가구인테리어/잡화_저가',
 'sum_분기_2014_4_가구인테리어/잡화_중가',
 'sum_분기_2014_4_가전/레저취미/멀티샵_고가',
 'sum_분기_2014_4_가전/레저취미/멀티샵_저가',
 'sum_분기_2014_4_가전/레저취미/멀티샵_중가',
 'sum_분기_2014_4_교육문화/아동_고가',
 'sum_분기_2014_4_교육문화/아동_저가',
 'sum_분기_2014_4_교육문화/아동_중가',
 'sum_분기_2014_4_식품/생활_고가',
 'sum_분기_2014_4_식품/생활_저가',
 'sum_분기_2014_4_식품/생활_중가',
 'sum_분기_2014_4_의류/이미용_고가',
 'sum_분기_2014_4_의류/이미용_저가',
 'sum_분기_2014_4_의류/이미용_중가',
 'sum_분기_2014_4_침구/주방_고가',
 'sum_분기_2014_4_침구/주방_저가',
 'sum_분기_2014_4_침구/주방_중가',
 'sum_분기_2015_1_가구인테리어/잡화_고가',
 'sum_분기_2015_1_가구인테리어/잡화_저가',
 'sum_분기_2015_1_가구인테리어/잡화_중가',
 'sum_분기_2015_1_가전/레저취미/멀티샵_고가',
 'sum_분기_2015_1_가전/레저취미/멀티샵_저가',
 'sum_분기_2015_1_가전/레저취미/멀티샵_중가',
 'sum_분기_2015_1_교육문화/아동_고가',
 'sum_분기_2015_1_교육문화/아동_저가',
 'sum_분기_2015_1_교육문화/아동_중가',
 'sum_분기_2015_1_식품/생활_고가',
 'sum_분기_2015_1_식품/생활_저가',
 'sum_분기_2015_1_식품/생활_중가',
 'sum_분기_2015_1_의류/이미용_고가',
 'sum_분기_2015_1_의류/이미용_저가',
 'sum_분기_2015_1_의류/이미용_중가',
 'sum_분기_2015_1_침구/주방_고가',
 'sum_분기_2015_1_침구/주방_저가',
 'sum_분기_2015_1_침구/주방_중가',
 'sum_분기_2015_2_가구인테리어/잡화_고가',
 'sum_분기_2015_2_가구인테리어/잡화_저가',
 'sum_분기_2015_2_가구인테리어/잡화_중가',
 'sum_분기_2015_2_가전/레저취미/멀티샵_고가',
 'sum_분기_2015_2_가전/레저취미/멀티샵_저가',
 'sum_분기_2015_2_가전/레저취미/멀티샵_중가',
 'sum_분기_2015_2_교육문화/아동_고가',
 'sum_분기_2015_2_교육문화/아동_저가',
 'sum_분기_2015_2_교육문화/아동_중가',
 'sum_분기_2015_2_식품/생활_고가',
 'sum_분기_2015_2_식품/생활_저가',
 'sum_분기_2015_2_식품/생활_중가',
 'sum_분기_2015_2_의류/이미용_고가',
 'sum_분기_2015_2_의류/이미용_저가',
 'sum_분기_2015_2_의류/이미용_중가',
 'sum_분기_2015_2_침구/주방_고가',
 'sum_분기_2015_2_침구/주방_저가',
 'sum_분기_2015_2_침구/주방_중가',
 'sum_분기_2015_3_가구인테리어/잡화_고가',
 'sum_분기_2015_3_가구인테리어/잡화_저가',
 'sum_분기_2015_3_가구인테리어/잡화_중가',
 'sum_분기_2015_3_가전/레저취미/멀티샵_고가',
 'sum_분기_2015_3_가전/레저취미/멀티샵_저가',
 'sum_분기_2015_3_가전/레저취미/멀티샵_중가',
 'sum_분기_2015_3_교육문화/아동_고가',
 'sum_분기_2015_3_교육문화/아동_저가',
 'sum_분기_2015_3_교육문화/아동_중가',
 'sum_분기_2015_3_식품/생활_고가',
 'sum_분기_2015_3_식품/생활_저가',
 'sum_분기_2015_3_식품/생활_중가',
 'sum_분기_2015_3_의류/이미용_고가',
 'sum_분기_2015_3_의류/이미용_저가',
 'sum_분기_2015_3_의류/이미용_중가',
 'sum_분기_2015_3_침구/주방_고가',
 'sum_분기_2015_3_침구/주방_저가',
 'sum_분기_2015_3_침구/주방_중가',
 'sum_분기_2015_4_가구인테리어/잡화_고가',
 'sum_분기_2015_4_가구인테리어/잡화_저가',
 'sum_분기_2015_4_가구인테리어/잡화_중가',
 'sum_분기_2015_4_가전/레저취미/멀티샵_고가',
 'sum_분기_2015_4_가전/레저취미/멀티샵_저가',
 'sum_분기_2015_4_가전/레저취미/멀티샵_중가',
 'sum_분기_2015_4_교육문화/아동_고가',
 'sum_분기_2015_4_교육문화/아동_저가',
 'sum_분기_2015_4_교육문화/아동_중가',
 'sum_분기_2015_4_식품/생활_고가',
 'sum_분기_2015_4_식품/생활_저가',
 'sum_분기_2015_4_식품/생활_중가',
 'sum_분기_2015_4_의류/이미용_고가',
 'sum_분기_2015_4_의류/이미용_저가',
 'sum_분기_2015_4_의류/이미용_중가',
 'sum_분기_2015_4_침구/주방_고가',
 'sum_분기_2015_4_침구/주방_저가',
 'sum_분기_2015_4_침구/주방_중가',
 'year_up',
 'year_label',
 'half_up',
 'half_label',
 'q_up',
 'q_label']

## 평균 구매금액

In [73]:
import re

In [74]:
new_sum_columns_name = []
for sum_column in purchase_pviot_sum.columns.tolist():
    new_sum_columns_name.append(re.sub('sum', '', sum_column))
new_sum_columns_name

['_2014_가구인테리어/잡화_고가',
 '_2014_가구인테리어/잡화_저가',
 '_2014_가구인테리어/잡화_중가',
 '_2014_가전/레저취미/멀티샵_고가',
 '_2014_가전/레저취미/멀티샵_저가',
 '_2014_가전/레저취미/멀티샵_중가',
 '_2014_교육문화/아동_고가',
 '_2014_교육문화/아동_저가',
 '_2014_교육문화/아동_중가',
 '_2014_식품/생활_고가',
 '_2014_식품/생활_저가',
 '_2014_식품/생활_중가',
 '_2014_의류/이미용_고가',
 '_2014_의류/이미용_저가',
 '_2014_의류/이미용_중가',
 '_2014_침구/주방_고가',
 '_2014_침구/주방_저가',
 '_2014_침구/주방_중가',
 '_2015_가구인테리어/잡화_고가',
 '_2015_가구인테리어/잡화_저가',
 '_2015_가구인테리어/잡화_중가',
 '_2015_가전/레저취미/멀티샵_고가',
 '_2015_가전/레저취미/멀티샵_저가',
 '_2015_가전/레저취미/멀티샵_중가',
 '_2015_교육문화/아동_고가',
 '_2015_교육문화/아동_저가',
 '_2015_교육문화/아동_중가',
 '_2015_식품/생활_고가',
 '_2015_식품/생활_저가',
 '_2015_식품/생활_중가',
 '_2015_의류/이미용_고가',
 '_2015_의류/이미용_저가',
 '_2015_의류/이미용_중가',
 '_2015_침구/주방_고가',
 '_2015_침구/주방_저가',
 '_2015_침구/주방_중가',
 '_반기_1_가구인테리어/잡화_고가',
 '_반기_1_가구인테리어/잡화_저가',
 '_반기_1_가구인테리어/잡화_중가',
 '_반기_1_가전/레저취미/멀티샵_고가',
 '_반기_1_가전/레저취미/멀티샵_저가',
 '_반기_1_가전/레저취미/멀티샵_중가',
 '_반기_1_교육문화/아동_고가',
 '_반기_1_교육문화/아동_저가',
 '_반기_1_교육문화/아동_중가',
 '_반기_1_식품/생활_고가',
 '_반기_1_식품/생활_저가',
 '_반기_1_식품/생활_중가',
 '_반기_1_의류/이미용_고가',
 '_반기_1_의류/이미용_저가',
 '_반기_1_의류/이미용_중가',
 '_반기_1_침구/주방_고가',
 '_반기_1_침구/주방_저가',
 '_반기_1_침구/주방_중가',
 '_반기_2_가구인테리어/잡화_고가',
 '_반기_2_가구인테리어/잡화_저가',
 '_반기_2_가구인테리어/잡화_중가',
 '_반기_2_가전/레저취미/멀티샵_고가',
 '_반기_2_가전/레저취미/멀티샵_저가',
 '_반기_2_가전/레저취미/멀티샵_중가',
 '_반기_2_교육문화/아동_고가',
 '_반기_2_교육문화/아동_저가',
 '_반기_2_교육문화/아동_중가',
 '_반기_2_식품/생활_고가',
 '_반기_2_식품/생활_저가',
 '_반기_2_식품/생활_중가',
 '_반기_2_의류/이미용_고가',
 '_반기_2_의류/이미용_저가',
 '_반기_2_의류/이미용_중가',
 '_반기_2_침구/주방_고가',
 '_반기_2_침구/주방_저가',
 '_반기_2_침구/주방_중가',
 '_반기_3_가구인테리어/잡화_고가',
 '_반기_3_가구인테리어/잡화_저가',
 '_반기_3_가구인테리어/잡화_중가',
 '_반기_3_가전/레저취미/멀티샵_고가',
 '_반기_3_가전/레저취미/멀티샵_저가',
 '_반기_3_가전/레저취미/멀티샵_중가',
 '_반기_3_교육문화/아동_고가',
 '_반기_3_교육문화/아동_저가',
 '_반기_3_교육문화/아동_중가',
 '_반기_3_식품/생활_고가',
 '_반기_3_식품/생활_저가',
 '_반기_3_식품/생활_중가',
 '_반기_3_의류/이미용_고가',
 '_반기_3_의류/이미용_저가',
 '_반기_3_의류/이미용_중가',
 '_반기_3_침구/주방_고가',
 '_반기_3_침구/주방_저가',
 '_반기_3_침구/주방_중가',
 '_반기_4_가구인테리어/잡화_고가',
 '_반기_4_가구인테리어/잡화_저가',
 '_반기_4_가구인테리어/잡화_중가',
 '_반기_4_가전/레저취미/멀티샵_고가',
 '_반기_4_가전/레저취미/멀티샵_저가',
 '_반기_4_가전/레저취미/멀티샵_중가',
 '_반기_4_교육문화/아동_고가',
 '_반기_4_교육문화/아동_저가',
 '_반기_4_교육문화/아동_중가',
 '_반기_4_식품/생활_고가',
 '_반기_4_식품/생활_저가',
 '_반기_4_식품/생활_중가',
 '_반기_4_의류/이미용_고가',
 '_반기_4_의류/이미용_저가',
 '_반기_4_의류/이미용_중가',
 '_반기_4_침구/주방_고가',
 '_반기_4_침구/주방_저가',
 '_반기_4_침구/주방_중가',
 '_분기_2014_1_가구인테리어/잡화_고가',
 '_분기_2014_1_가구인테리어/잡화_저가',
 '_분기_2014_1_가구인테리어/잡화_중가',
 '_분기_2014_1_가전/레저취미/멀티샵_고가',
 '_분기_2014_1_가전/레저취미/멀티샵_저가',
 '_분기_2014_1_가전/레저취미/멀티샵_중가',
 '_분기_2014_1_교육문화/아동_고가',
 '_분기_2014_1_교육문화/아동_저가',
 '_분기_2014_1_교육문화/아동_중가',
 '_분기_2014_1_식품/생활_고가',
 '_분기_2014_1_식품/생활_저가',
 '_분기_2014_1_식품/생활_중가',
 '_분기_2014_1_의류/이미용_고가',
 '_분기_2014_1_의류/이미용_저가',
 '_분기_2014_1_의류/이미용_중가',
 '_분기_2014_1_침구/주방_고가',
 '_분기_2014_1_침구/주방_저가',
 '_분기_2014_1_침구/주방_중가',
 '_분기_2014_2_가구인테리어/잡화_고가',
 '_분기_2014_2_가구인테리어/잡화_저가',
 '_분기_2014_2_가구인테리어/잡화_중가',
 '_분기_2014_2_가전/레저취미/멀티샵_고가',
 '_분기_2014_2_가전/레저취미/멀티샵_저가',
 '_분기_2014_2_가전/레저취미/멀티샵_중가',
 '_분기_2014_2_교육문화/아동_고가',
 '_분기_2014_2_교육문화/아동_저가',
 '_분기_2014_2_교육문화/아동_중가',
 '_분기_2014_2_식품/생활_고가',
 '_분기_2014_2_식품/생활_저가',
 '_분기_2014_2_식품/생활_중가',
 '_분기_2014_2_의류/이미용_고가',
 '_분기_2014_2_의류/이미용_저가',
 '_분기_2014_2_의류/이미용_중가',
 '_분기_2014_2_침구/주방_고가',
 '_분기_2014_2_침구/주방_저가',
 '_분기_2014_2_침구/주방_중가',
 '_분기_2014_3_가구인테리어/잡화_고가',
 '_분기_2014_3_가구인테리어/잡화_저가',
 '_분기_2014_3_가구인테리어/잡화_중가',
 '_분기_2014_3_가전/레저취미/멀티샵_고가',
 '_분기_2014_3_가전/레저취미/멀티샵_저가',
 '_분기_2014_3_가전/레저취미/멀티샵_중가',
 '_분기_2014_3_교육문화/아동_고가',
 '_분기_2014_3_교육문화/아동_저가',
 '_분기_2014_3_교육문화/아동_중가',
 '_분기_2014_3_식품/생활_고가',
 '_분기_2014_3_식품/생활_저가',
 '_분기_2014_3_식품/생활_중가',
 '_분기_2014_3_의류/이미용_고가',
 '_분기_2014_3_의류/이미용_저가',
 '_분기_2014_3_의류/이미용_중가',
 '_분기_2014_3_침구/주방_고가',
 '_분기_2014_3_침구/주방_저가',
 '_분기_2014_3_침구/주방_중가',
 '_분기_2014_4_가구인테리어/잡화_고가',
 '_분기_2014_4_가구인테리어/잡화_저가',
 '_분기_2014_4_가구인테리어/잡화_중가',
 '_분기_2014_4_가전/레저취미/멀티샵_고가',
 '_분기_2014_4_가전/레저취미/멀티샵_저가',
 '_분기_2014_4_가전/레저취미/멀티샵_중가',
 '_분기_2014_4_교육문화/아동_고가',
 '_분기_2014_4_교육문화/아동_저가',
 '_분기_2014_4_교육문화/아동_중가',
 '_분기_2014_4_식품/생활_고가',
 '_분기_2014_4_식품/생활_저가',
 '_분기_2014_4_식품/생활_중가',
 '_분기_2014_4_의류/이미용_고가',
 '_분기_2014_4_의류/이미용_저가',
 '_분기_2014_4_의류/이미용_중가',
 '_분기_2014_4_침구/주방_고가',
 '_분기_2014_4_침구/주방_저가',
 '_분기_2014_4_침구/주방_중가',
 '_분기_2015_1_가구인테리어/잡화_고가',
 '_분기_2015_1_가구인테리어/잡화_저가',
 '_분기_2015_1_가구인테리어/잡화_중가',
 '_분기_2015_1_가전/레저취미/멀티샵_고가',
 '_분기_2015_1_가전/레저취미/멀티샵_저가',
 '_분기_2015_1_가전/레저취미/멀티샵_중가',
 '_분기_2015_1_교육문화/아동_고가',
 '_분기_2015_1_교육문화/아동_저가',
 '_분기_2015_1_교육문화/아동_중가',
 '_분기_2015_1_식품/생활_고가',
 '_분기_2015_1_식품/생활_저가',
 '_분기_2015_1_식품/생활_중가',
 '_분기_2015_1_의류/이미용_고가',
 '_분기_2015_1_의류/이미용_저가',
 '_분기_2015_1_의류/이미용_중가',
 '_분기_2015_1_침구/주방_고가',
 '_분기_2015_1_침구/주방_저가',
 '_분기_2015_1_침구/주방_중가',
 '_분기_2015_2_가구인테리어/잡화_고가',
 '_분기_2015_2_가구인테리어/잡화_저가',
 '_분기_2015_2_가구인테리어/잡화_중가',
 '_분기_2015_2_가전/레저취미/멀티샵_고가',
 '_분기_2015_2_가전/레저취미/멀티샵_저가',
 '_분기_2015_2_가전/레저취미/멀티샵_중가',
 '_분기_2015_2_교육문화/아동_고가',
 '_분기_2015_2_교육문화/아동_저가',
 '_분기_2015_2_교육문화/아동_중가',
 '_분기_2015_2_식품/생활_고가',
 '_분기_2015_2_식품/생활_저가',
 '_분기_2015_2_식품/생활_중가',
 '_분기_2015_2_의류/이미용_고가',
 '_분기_2015_2_의류/이미용_저가',
 '_분기_2015_2_의류/이미용_중가',
 '_분기_2015_2_침구/주방_고가',
 '_분기_2015_2_침구/주방_저가',
 '_분기_2015_2_침구/주방_중가',
 '_분기_2015_3_가구인테리어/잡화_고가',
 '_분기_2015_3_가구인테리어/잡화_저가',
 '_분기_2015_3_가구인테리어/잡화_중가',
 '_분기_2015_3_가전/레저취미/멀티샵_고가',
 '_분기_2015_3_가전/레저취미/멀티샵_저가',
 '_분기_2015_3_가전/레저취미/멀티샵_중가',
 '_분기_2015_3_교육문화/아동_고가',
 '_분기_2015_3_교육문화/아동_저가',
 '_분기_2015_3_교육문화/아동_중가',
 '_분기_2015_3_식품/생활_고가',
 '_분기_2015_3_식품/생활_저가',
 '_분기_2015_3_식품/생활_중가',
 '_분기_2015_3_의류/이미용_고가',
 '_분기_2015_3_의류/이미용_저가',
 '_분기_2015_3_의류/이미용_중가',
 '_분기_2015_3_침구/주방_고가',
 '_분기_2015_3_침구/주방_저가',
 '_분기_2015_3_침구/주방_중가',
 '_분기_2015_4_가구인테리어/잡화_고가',
 '_분기_2015_4_가구인테리어/잡화_저가',
 '_분기_2015_4_가구인테리어/잡화_중가',
 '_분기_2015_4_가전/레저취미/멀티샵_고가',
 '_분기_2015_4_가전/레저취미/멀티샵_저가',
 '_분기_2015_4_가전/레저취미/멀티샵_중가',
 '_분기_2015_4_교육문화/아동_고가',
 '_분기_2015_4_교육문화/아동_저가',
 '_분기_2015_4_교육문화/아동_중가',
 '_분기_2015_4_식품/생활_고가',
 '_분기_2015_4_식품/생활_저가',
 '_분기_2015_4_식품/생활_중가',
 '_분기_2015_4_의류/이미용_고가',
 '_분기_2015_4_의류/이미용_저가',
 '_분기_2015_4_의류/이미용_중가',
 '_분기_2015_4_침구/주방_고가',
 '_분기_2015_4_침구/주방_저가',
 '_분기_2015_4_침구/주방_중가',
 'year_up',
 'year_label',
 'half_up',
 'half_label',
 'q_up',
 'q_label']

In [75]:
purchase_pviot_sum_copy = purchase_pviot_sum.copy()
purchase_pviot_sum_copy.columns = new_cnt_columns_name
purchase_pviot_sum_copy

,_2014_가구인테리어/잡화_고가,_2014_가구인테리어/잡화_저가,_2014_가구인테리어/잡화_중가,_2014_가전/레저취미/멀티샵_고가,_2014_가전/레저취미/멀티샵_저가,_2014_가전/레저취미/멀티샵_중가,_2014_교육문화/아동_고가,_2014_교육문화/아동_저가,_2014_교육문화/아동_중가,_2014_식품/생활_고가,...,_분기_2015_4_의류/이미용_중가,_분기_2015_4_침구/주방_고가,_분기_2015_4_침구/주방_저가,_분기_2015_4_침구/주방_중가,year_up,year_label,half_up,half_label,q_up,q_label
CUSTNO,,,,,,,,,,,,,,,,,,,,,
1,236550.0,1848200.0,1366400.0,8791650.0,0.0,130450.0,0.0,0.0,177460.0,4167867.0,...,3415160.0,137750.0,0.0,699200.0,-23040784.0,0,-6822837.0,0,-3845652.0,0
2,434150.0,1970530.0,461690.0,6410030.0,60500.0,244650.0,0.0,0.0,577050.0,1690010.0,...,3002000.0,0.0,0.0,432490.0,7390100.0,1,1520590.0,1,-2122250.0,0
3,0.0,9950.0,0.0,0.0,26900.0,0.0,0.0,0.0,0.0,121170.0,...,0.0,0.0,0.0,0.0,-622371.0,0,-172097.0,0,-44681.0,0
4,0.0,633710.0,520520.0,447350.0,5200.0,568100.0,0.0,0.0,0.0,106164.0,...,565980.0,0.0,0.0,54000.0,-1905422.0,0,-1304849.0,0,300502.0,1
5,57000.0,515380.0,197570.0,49900.0,0.0,134280.0,0.0,0.0,74200.0,1265640.0,...,717050.0,0.0,0.0,0.0,-2134690.0,0,-2843890.0,0,-529070.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19379,0.0,3150.0,449900.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,346780.0,0.0,0.0,0.0,3398040.0,1,2192740.0,1,1387190.0,1
19380,0.0,3000.0,0.0,0.0,9900.0,0.0,0.0,0.0,0.0,0.0,...,574000.0,0.0,0.0,0.0,2867577.0,1,2552327.0,1,2183420.0,1
19381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,78200.0,31600.0,6040669.0,1,3243498.0,1,1375997.0,1
19382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,12670.0,2900.0,4401773.0,1,2575034.0,1,1308847.0,1
19383,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,467900.0,0.0,0.0,0.0,2384400.0,1,2357400.0,1,1265040.0,1

In [76]:
new_cnt_columns_name = []
for cnt_column in purchase_pviot_cnt.columns.tolist():
    new_cnt_columns_name.append(re.sub('count', '', cnt_column))
new_cnt_columns_name

['_2014_가구인테리어/잡화_고가',
 '_2014_가구인테리어/잡화_저가',
 '_2014_가구인테리어/잡화_중가',
 '_2014_가전/레저취미/멀티샵_고가',
 '_2014_가전/레저취미/멀티샵_저가',
 '_2014_가전/레저취미/멀티샵_중가',
 '_2014_교육문화/아동_고가',
 '_2014_교육문화/아동_저가',
 '_2014_교육문화/아동_중가',
 '_2014_식품/생활_고가',
 '_2014_식품/생활_저가',
 '_2014_식품/생활_중가',
 '_2014_의류/이미용_고가',
 '_2014_의류/이미용_저가',
 '_2014_의류/이미용_중가',
 '_2014_침구/주방_고가',
 '_2014_침구/주방_저가',
 '_2014_침구/주방_중가',
 '_2015_가구인테리어/잡화_고가',
 '_2015_가구인테리어/잡화_저가',
 '_2015_가구인테리어/잡화_중가',
 '_2015_가전/레저취미/멀티샵_고가',
 '_2015_가전/레저취미/멀티샵_저가',
 '_2015_가전/레저취미/멀티샵_중가',
 '_2015_교육문화/아동_고가',
 '_2015_교육문화/아동_저가',
 '_2015_교육문화/아동_중가',
 '_2015_식품/생활_고가',
 '_2015_식품/생활_저가',
 '_2015_식품/생활_중가',
 '_2015_의류/이미용_고가',
 '_2015_의류/이미용_저가',
 '_2015_의류/이미용_중가',
 '_2015_침구/주방_고가',
 '_2015_침구/주방_저가',
 '_2015_침구/주방_중가',
 '_반기_1_가구인테리어/잡화_고가',
 '_반기_1_가구인테리어/잡화_저가',
 '_반기_1_가구인테리어/잡화_중가',
 '_반기_1_가전/레저취미/멀티샵_고가',
 '_반기_1_가전/레저취미/멀티샵_저가',
 '_반기_1_가전/레저취미/멀티샵_중가',
 '_반기_1_교육문화/아동_고가',
 '_반기_1_교육문화/아동_저가',
 '_반기_1_교육문화/아동_중가',
 '_반기_1_식품/생활_고가',
 '_반기_1_식품/생활_저가',
 '_반기_1_식품/생활_중가',
 '_반기_1_의류/이미용_고가',
 '_반기_1_의류/이미용_저가',
 '_반기_1_의류/이미용_중가',
 '_반기_1_침구/주방_고가',
 '_반기_1_침구/주방_저가',
 '_반기_1_침구/주방_중가',
 '_반기_2_가구인테리어/잡화_고가',
 '_반기_2_가구인테리어/잡화_저가',
 '_반기_2_가구인테리어/잡화_중가',
 '_반기_2_가전/레저취미/멀티샵_고가',
 '_반기_2_가전/레저취미/멀티샵_저가',
 '_반기_2_가전/레저취미/멀티샵_중가',
 '_반기_2_교육문화/아동_고가',
 '_반기_2_교육문화/아동_저가',
 '_반기_2_교육문화/아동_중가',
 '_반기_2_식품/생활_고가',
 '_반기_2_식품/생활_저가',
 '_반기_2_식품/생활_중가',
 '_반기_2_의류/이미용_고가',
 '_반기_2_의류/이미용_저가',
 '_반기_2_의류/이미용_중가',
 '_반기_2_침구/주방_고가',
 '_반기_2_침구/주방_저가',
 '_반기_2_침구/주방_중가',
 '_반기_3_가구인테리어/잡화_고가',
 '_반기_3_가구인테리어/잡화_저가',
 '_반기_3_가구인테리어/잡화_중가',
 '_반기_3_가전/레저취미/멀티샵_고가',
 '_반기_3_가전/레저취미/멀티샵_저가',
 '_반기_3_가전/레저취미/멀티샵_중가',
 '_반기_3_교육문화/아동_고가',
 '_반기_3_교육문화/아동_저가',
 '_반기_3_교육문화/아동_중가',
 '_반기_3_식품/생활_고가',
 '_반기_3_식품/생활_저가',
 '_반기_3_식품/생활_중가',
 '_반기_3_의류/이미용_고가',
 '_반기_3_의류/이미용_저가',
 '_반기_3_의류/이미용_중가',
 '_반기_3_침구/주방_고가',
 '_반기_3_침구/주방_저가',
 '_반기_3_침구/주방_중가',
 '_반기_4_가구인테리어/잡화_고가',
 '_반기_4_가구인테리어/잡화_저가',
 '_반기_4_가구인테리어/잡화_중가',
 '_반기_4_가전/레저취미/멀티샵_고가',
 '_반기_4_가전/레저취미/멀티샵_저가',
 '_반기_4_가전/레저취미/멀티샵_중가',
 '_반기_4_교육문화/아동_고가',
 '_반기_4_교육문화/아동_저가',
 '_반기_4_교육문화/아동_중가',
 '_반기_4_식품/생활_고가',
 '_반기_4_식품/생활_저가',
 '_반기_4_식품/생활_중가',
 '_반기_4_의류/이미용_고가',
 '_반기_4_의류/이미용_저가',
 '_반기_4_의류/이미용_중가',
 '_반기_4_침구/주방_고가',
 '_반기_4_침구/주방_저가',
 '_반기_4_침구/주방_중가',
 '_분기_2014_1_가구인테리어/잡화_고가',
 '_분기_2014_1_가구인테리어/잡화_저가',
 '_분기_2014_1_가구인테리어/잡화_중가',
 '_분기_2014_1_가전/레저취미/멀티샵_고가',
 '_분기_2014_1_가전/레저취미/멀티샵_저가',
 '_분기_2014_1_가전/레저취미/멀티샵_중가',
 '_분기_2014_1_교육문화/아동_고가',
 '_분기_2014_1_교육문화/아동_저가',
 '_분기_2014_1_교육문화/아동_중가',
 '_분기_2014_1_식품/생활_고가',
 '_분기_2014_1_식품/생활_저가',
 '_분기_2014_1_식품/생활_중가',
 '_분기_2014_1_의류/이미용_고가',
 '_분기_2014_1_의류/이미용_저가',
 '_분기_2014_1_의류/이미용_중가',
 '_분기_2014_1_침구/주방_고가',
 '_분기_2014_1_침구/주방_저가',
 '_분기_2014_1_침구/주방_중가',
 '_분기_2014_2_가구인테리어/잡화_고가',
 '_분기_2014_2_가구인테리어/잡화_저가',
 '_분기_2014_2_가구인테리어/잡화_중가',
 '_분기_2014_2_가전/레저취미/멀티샵_고가',
 '_분기_2014_2_가전/레저취미/멀티샵_저가',
 '_분기_2014_2_가전/레저취미/멀티샵_중가',
 '_분기_2014_2_교육문화/아동_고가',
 '_분기_2014_2_교육문화/아동_저가',
 '_분기_2014_2_교육문화/아동_중가',
 '_분기_2014_2_식품/생활_고가',
 '_분기_2014_2_식품/생활_저가',
 '_분기_2014_2_식품/생활_중가',
 '_분기_2014_2_의류/이미용_고가',
 '_분기_2014_2_의류/이미용_저가',
 '_분기_2014_2_의류/이미용_중가',
 '_분기_2014_2_침구/주방_고가',
 '_분기_2014_2_침구/주방_저가',
 '_분기_2014_2_침구/주방_중가',
 '_분기_2014_3_가구인테리어/잡화_고가',
 '_분기_2014_3_가구인테리어/잡화_저가',
 '_분기_2014_3_가구인테리어/잡화_중가',
 '_분기_2014_3_가전/레저취미/멀티샵_고가',
 '_분기_2014_3_가전/레저취미/멀티샵_저가',
 '_분기_2014_3_가전/레저취미/멀티샵_중가',
 '_분기_2014_3_교육문화/아동_고가',
 '_분기_2014_3_교육문화/아동_저가',
 '_분기_2014_3_교육문화/아동_중가',
 '_분기_2014_3_식품/생활_고가',
 '_분기_2014_3_식품/생활_저가',
 '_분기_2014_3_식품/생활_중가',
 '_분기_2014_3_의류/이미용_고가',
 '_분기_2014_3_의류/이미용_저가',
 '_분기_2014_3_의류/이미용_중가',
 '_분기_2014_3_침구/주방_고가',
 '_분기_2014_3_침구/주방_저가',
 '_분기_2014_3_침구/주방_중가',
 '_분기_2014_4_가구인테리어/잡화_고가',
 '_분기_2014_4_가구인테리어/잡화_저가',
 '_분기_2014_4_가구인테리어/잡화_중가',
 '_분기_2014_4_가전/레저취미/멀티샵_고가',
 '_분기_2014_4_가전/레저취미/멀티샵_저가',
 '_분기_2014_4_가전/레저취미/멀티샵_중가',
 '_분기_2014_4_교육문화/아동_고가',
 '_분기_2014_4_교육문화/아동_저가',
 '_분기_2014_4_교육문화/아동_중가',
 '_분기_2014_4_식품/생활_고가',
 '_분기_2014_4_식품/생활_저가',
 '_분기_2014_4_식품/생활_중가',
 '_분기_2014_4_의류/이미용_고가',
 '_분기_2014_4_의류/이미용_저가',
 '_분기_2014_4_의류/이미용_중가',
 '_분기_2014_4_침구/주방_고가',
 '_분기_2014_4_침구/주방_저가',
 '_분기_2014_4_침구/주방_중가',
 '_분기_2015_1_가구인테리어/잡화_고가',
 '_분기_2015_1_가구인테리어/잡화_저가',
 '_분기_2015_1_가구인테리어/잡화_중가',
 '_분기_2015_1_가전/레저취미/멀티샵_고가',
 '_분기_2015_1_가전/레저취미/멀티샵_저가',
 '_분기_2015_1_가전/레저취미/멀티샵_중가',
 '_분기_2015_1_교육문화/아동_고가',
 '_분기_2015_1_교육문화/아동_저가',
 '_분기_2015_1_교육문화/아동_중가',
 '_분기_2015_1_식품/생활_고가',
 '_분기_2015_1_식품/생활_저가',
 '_분기_2015_1_식품/생활_중가',
 '_분기_2015_1_의류/이미용_고가',
 '_분기_2015_1_의류/이미용_저가',
 '_분기_2015_1_의류/이미용_중가',
 '_분기_2015_1_침구/주방_고가',
 '_분기_2015_1_침구/주방_저가',
 '_분기_2015_1_침구/주방_중가',
 '_분기_2015_2_가구인테리어/잡화_고가',
 '_분기_2015_2_가구인테리어/잡화_저가',
 '_분기_2015_2_가구인테리어/잡화_중가',
 '_분기_2015_2_가전/레저취미/멀티샵_고가',
 '_분기_2015_2_가전/레저취미/멀티샵_저가',
 '_분기_2015_2_가전/레저취미/멀티샵_중가',
 '_분기_2015_2_교육문화/아동_고가',
 '_분기_2015_2_교육문화/아동_저가',
 '_분기_2015_2_교육문화/아동_중가',
 '_분기_2015_2_식품/생활_고가',
 '_분기_2015_2_식품/생활_저가',
 '_분기_2015_2_식품/생활_중가',
 '_분기_2015_2_의류/이미용_고가',
 '_분기_2015_2_의류/이미용_저가',
 '_분기_2015_2_의류/이미용_중가',
 '_분기_2015_2_침구/주방_고가',
 '_분기_2015_2_침구/주방_저가',
 '_분기_2015_2_침구/주방_중가',
 '_분기_2015_3_가구인테리어/잡화_고가',
 '_분기_2015_3_가구인테리어/잡화_저가',
 '_분기_2015_3_가구인테리어/잡화_중가',
 '_분기_2015_3_가전/레저취미/멀티샵_고가',
 '_분기_2015_3_가전/레저취미/멀티샵_저가',
 '_분기_2015_3_가전/레저취미/멀티샵_중가',
 '_분기_2015_3_교육문화/아동_고가',
 '_분기_2015_3_교육문화/아동_저가',
 '_분기_2015_3_교육문화/아동_중가',
 '_분기_2015_3_식품/생활_고가',
 '_분기_2015_3_식품/생활_저가',
 '_분기_2015_3_식품/생활_중가',
 '_분기_2015_3_의류/이미용_고가',
 '_분기_2015_3_의류/이미용_저가',
 '_분기_2015_3_의류/이미용_중가',
 '_분기_2015_3_침구/주방_고가',
 '_분기_2015_3_침구/주방_저가',
 '_분기_2015_3_침구/주방_중가',
 '_분기_2015_4_가구인테리어/잡화_고가',
 '_분기_2015_4_가구인테리어/잡화_저가',
 '_분기_2015_4_가구인테리어/잡화_중가',
 '_분기_2015_4_가전/레저취미/멀티샵_고가',
 '_분기_2015_4_가전/레저취미/멀티샵_저가',
 '_분기_2015_4_가전/레저취미/멀티샵_중가',
 '_분기_2015_4_교육문화/아동_고가',
 '_분기_2015_4_교육문화/아동_저가',
 '_분기_2015_4_교육문화/아동_중가',
 '_분기_2015_4_식품/생활_고가',
 '_분기_2015_4_식품/생활_저가',
 '_분기_2015_4_식품/생활_중가',
 '_분기_2015_4_의류/이미용_고가',
 '_분기_2015_4_의류/이미용_저가',
 '_분기_2015_4_의류/이미용_중가',
 '_분기_2015_4_침구/주방_고가',
 '_분기_2015_4_침구/주방_저가',
 '_분기_2015_4_침구/주방_중가',
 'year_up',
 'year_label',
 'half_up',
 'half_label',
 'q_up',
 'q_label']

In [77]:
purchase_pviot_cnt_copy = purchase_pviot_cnt.copy()
purchase_pviot_cnt_copy.columns = new_cnt_columns_name
purchase_pviot_cnt_copy

,_2014_가구인테리어/잡화_고가,_2014_가구인테리어/잡화_저가,_2014_가구인테리어/잡화_중가,_2014_가전/레저취미/멀티샵_고가,_2014_가전/레저취미/멀티샵_저가,_2014_가전/레저취미/멀티샵_중가,_2014_교육문화/아동_고가,_2014_교육문화/아동_저가,_2014_교육문화/아동_중가,_2014_식품/생활_고가,...,_분기_2015_4_의류/이미용_중가,_분기_2015_4_침구/주방_고가,_분기_2015_4_침구/주방_저가,_분기_2015_4_침구/주방_중가,year_up,year_label,half_up,half_label,q_up,q_label
CUSTNO,,,,,,,,,,,,,,,,,,,,,
1,1.0,23.0,11.0,13.0,0.0,3.0,0.0,0.0,2.0,49.0,...,17.0,2.0,0.0,1.0,-23040784.0,0,-6822837.0,0,-3845652.0,0
2,1.0,51.0,3.0,17.0,3.0,2.0,0.0,0.0,4.0,46.0,...,8.0,0.0,0.0,3.0,7390100.0,1,1520590.0,1,-2122250.0,0
3,0.0,89.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,-622371.0,0,-172097.0,0,-44681.0,0
4,0.0,21.0,4.0,4.0,1.0,4.0,0.0,0.0,0.0,9.0,...,8.0,0.0,0.0,2.0,-1905422.0,0,-1304849.0,0,300502.0,1
5,1.0,34.0,2.0,1.0,0.0,2.0,0.0,0.0,2.0,47.0,...,2.0,0.0,0.0,0.0,-2134690.0,0,-2843890.0,0,-529070.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19379,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.0,0.0,0.0,0.0,3398040.0,1,2192740.0,1,1387190.0,1
19380,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,9.0,0.0,0.0,0.0,2867577.0,1,2552327.0,1,2183420.0,1
19381,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,12.0,1.0,6040669.0,1,3243498.0,1,1375997.0,1
19382,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.0,1.0,4401773.0,1,2575034.0,1,1308847.0,1
19383,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,0.0,0.0,0.0,2384400.0,1,2357400.0,1,1265040.0,1

In [78]:
purchase_pviot_mean = purchase_pviot_sum_copy/purchase_pviot_cnt_copy
purchase_pviot_mean.fillna(0, inplace = True)
purchase_pviot_mean

,_2014_가구인테리어/잡화_고가,_2014_가구인테리어/잡화_저가,_2014_가구인테리어/잡화_중가,_2014_가전/레저취미/멀티샵_고가,_2014_가전/레저취미/멀티샵_저가,_2014_가전/레저취미/멀티샵_중가,_2014_교육문화/아동_고가,_2014_교육문화/아동_저가,_2014_교육문화/아동_중가,_2014_식품/생활_고가,...,_분기_2015_4_의류/이미용_중가,_분기_2015_4_침구/주방_고가,_분기_2015_4_침구/주방_저가,_분기_2015_4_침구/주방_중가,year_up,year_label,half_up,half_label,q_up,q_label
CUSTNO,,,,,,,,,,,,,,,,,,,,,
1,236550.0,80356.521739,124218.181818,676280.769231,0.000000,43483.333333,0.0,0.0,88730.0,85058.510204,...,200891.764706,68875.0,0.000000,699200.000000,1.0,0.0,1.0,0.0,1.0,0.0
2,434150.0,38637.843137,153896.666667,377060.588235,20166.666667,122325.000000,0.0,0.0,144262.5,36739.347826,...,375250.000000,0.0,0.000000,144163.333333,1.0,1.0,1.0,1.0,1.0,0.0
3,0.0,111.797753,0.000000,0.000000,26900.000000,0.000000,0.0,0.0,0.0,13463.333333,...,0.000000,0.0,0.000000,0.000000,1.0,0.0,1.0,0.0,1.0,0.0
4,0.0,30176.666667,130130.000000,111837.500000,5200.000000,142025.000000,0.0,0.0,0.0,11796.000000,...,70747.500000,0.0,0.000000,27000.000000,1.0,0.0,1.0,0.0,1.0,1.0
5,57000.0,15158.235294,98785.000000,49900.000000,0.000000,67140.000000,0.0,0.0,37100.0,26928.510638,...,358525.000000,0.0,0.000000,0.000000,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19379,0.0,3150.000000,112475.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,43347.500000,0.0,0.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
19380,0.0,3000.000000,0.000000,0.000000,9900.000000,0.000000,0.0,0.0,0.0,0.000000,...,63777.777778,0.0,0.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
19381,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.0,6516.666667,31600.000000,1.0,1.0,1.0,1.0,1.0,1.0
19382,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.0,3167.500000,2900.000000,1.0,1.0,1.0,1.0,1.0,1.0
19383,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,...,51988.888889,0.0,0.000000,0.000000,1.0,1.0,1.0,1.0,1.0,1.0

# 재시작

## 유지고객 분류

In [96]:
purchase_real.head()

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
0,17485,B,8919510,식품/생활,식품,샐러드채소,양상추,일용품,2015,4,3,저가,2000,2015_3
1,17485,B,8919510,식품/생활,식품,김치채소,무우,일용품,2015,4,3,저가,1250,2015_3
2,17485,B,8919510,식품/생활,식품,일반한우,한우양지,일용품,2015,4,3,고가,23790,2015_3
3,17485,B,8919510,식품/생활,식품,포도,캠벨포도,일용품,2015,4,3,중가,25600,2015_3
4,17485,B,8919510,식품/생활,식품,메론,머스크메론,일용품,2015,4,3,중가,12800,2015_3

In [97]:
cust_유지 = pd.pivot_table(data = purchase_real,
                           index = 'CUSTNO',
                           columns = ['PURYEAR', 'QUARTER'],
                           values = 'RNO',
                           aggfunc = 'count')
cust_유지

PURYEAR   2014                        2015
QUARTER      1      2      3      4      1      2      3      4
CUSTNO
1        121.0  117.0  142.0  214.0  172.0  140.0   73.0   78.0
2        184.0  155.0  139.0  132.0  145.0  116.0  126.0  119.0
3        139.0  209.0  246.0  145.0   87.0  133.0  139.0   93.0
4         93.0  177.0   85.0   87.0  122.0  141.0  118.0  107.0
5        184.0  193.0  110.0   20.0   93.0   30.0    NaN   89.0
...        ...    ...    ...    ...    ...    ...    ...    ...
19379      NaN    NaN   11.0   76.0  125.0  137.0  121.0  114.0
19380      NaN    NaN    NaN   17.0   62.0   41.0   52.0  268.0
19381      NaN    NaN    NaN    NaN  142.0  227.0  232.0  204.0
19382      NaN    NaN    NaN    NaN  174.0  224.0  231.0  277.0
19383      NaN    NaN    NaN    NaN    NaN    5.0  126.0  129.0

[19383 rows x 8 columns]

In [105]:
idx_유지 = cust_유지.dropna(axis = 0).index
idx_유지

Int64Index([    1,     2,     3,     4,     6,     7,     8,     9,    10,
               11,
            ...
            19328, 19329, 19330, 19331, 19332, 19333, 19334, 19335, 19336,
            19337],
           dtype='int64', name='CUSTNO', length=18866)

In [109]:
purchase_유지 = purchase_real[purchase_real['CUSTNO'].isin(idx_유지)]
purchase_유지

,CUSTNO,ASSO,RNO,BBCL,BCL,MCL,SCL,TYPE,PURYEAR,HALF_YEAR,QUARTER,PRICE_TYPE,PURAMT,Q_year
0,17485,B,8919510,식품/생활,식품,샐러드채소,양상추,일용품,2015,4,3,저가,2000,2015_3
1,17485,B,8919510,식품/생활,식품,김치채소,무우,일용품,2015,4,3,저가,1250,2015_3
2,17485,B,8919510,식품/생활,식품,일반한우,한우양지,일용품,2015,4,3,고가,23790,2015_3
3,17485,B,8919510,식품/생활,식품,포도,캠벨포도,일용품,2015,4,3,중가,25600,2015_3
4,17485,B,8919510,식품/생활,식품,메론,머스크메론,일용품,2015,4,3,중가,12800,2015_3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28593024,16515,B,7784996,식품/생활,식품,족발,즉석족발,일용품,2014,1,2,중가,4979,2014_2
28593025,5786,B,7784894,식품/생활,식품,스낵,일반스낵,일용품,2014,1,2,중가,490,2014_2
28593026,14026,B,7784900,식품/생활,식품,족발,냉장족발,일용품,2014,1,2,중가,4000,2014_2
28593027,16612,C,9500419,식품/생활,식품,기타축산,돼지양념육,일용품,2014,2,3,중가,7900,2014_3
28593028,7565,C,10737145,식품/생활,식품,우유,일반우유,일용품,2014,2,4,저가,5200,2014_4

## 카테고리 가중치 계산

In [114]:
category_sum = pd.pivot_table(data = purchase_유지,
                               index = ['BBCL'],
                               columns = ['PURYEAR', 'QUARTER'],
                               values = ['PURAMT'],
                               aggfunc = 'sum')
category_sum

                  PURAMT                                                      \
PURYEAR             2014                                                2015
QUARTER                1            2            3            4            1
BBCL
가구인테리어/잡화    12793337996  14248503000  12907656420  17935715680  14620753780
가전/레저취미/멀티샵   7696893420   9103224510   7137559410  10468393950   7866550399
교육문화/아동       2669314710   2876933455   2510325650   3496103031   2932233482
식품/생활        23585081099  22791291174  25198028033  22686448471  25258230990
의류/이미용       27397021458  26934670193  22872190565  36724315925  29195916129
침구/주방         3301991050   4013359522   3519002771   4023217175   3360756725


PURYEAR
QUARTER                2            3            4
BBCL
가구인테리어/잡화    16546938432  14395137922  19099339590
가전/레저취미/멀티샵   8720896521   7460668346  10959453759
교육문화/아동       2943134445   2522876050   3389468990
식품/생활        23022337673  26364027891  22533598244
의류/이미용       28370761620  23727095859  36488401680
침구/주방         3937420835   3466805599   4351742969

In [125]:
cate_sum_2014 = category_sum.iloc[:,:4]
cate_sum_2014.columns = [1,2,3,4]
cate_sum_2014

                       1            2            3            4
BBCL
가구인테리어/잡화    12793337996  14248503000  12907656420  17935715680
가전/레저취미/멀티샵   7696893420   9103224510   7137559410  10468393950
교육문화/아동       2669314710   2876933455   2510325650   3496103031
식품/생활        23585081099  22791291174  25198028033  22686448471
의류/이미용       27397021458  26934670193  22872190565  36724315925
침구/주방         3301991050   4013359522   3519002771   4023217175

In [124]:
cate_sum_2015 = category_sum.iloc[:,4:]
cate_sum_2015.columns = [1,2,3,4]
cate_sum_2015

                       1            2            3            4
BBCL
가구인테리어/잡화    14620753780  16546938432  14395137922  19099339590
가전/레저취미/멀티샵   7866550399   8720896521   7460668346  10959453759
교육문화/아동       2932233482   2943134445   2522876050   3389468990
식품/생활        25258230990  23022337673  26364027891  22533598244
의류/이미용       29195916129  28370761620  23727095859  36488401680
침구/주방         3360756725   3937420835   3466805599   4351742969

### 분기별/카테고리별 평균값

In [137]:
pd.options.display.float_format = '{:.1f}'.format
q_cate_mean_df = (cate_sum_2014 + cate_sum_2015)/2
q_cate_mean_df

                        1             2             3             4
BBCL
가구인테리어/잡화   13707045888.0 15397720716.0 13651397171.0 18517527635.0
가전/레저취미/멀티샵  7781721909.5  8912060515.5  7299113878.0 10713923854.5
교육문화/아동      2800774096.0  2910033950.0  2516600850.0  3442786010.5
식품/생활       24421656044.5 22906814423.5 25781027962.0 22610023357.5
의류/이미용      28296468793.5 27652715906.5 23299643212.0 36606358802.5
침구/주방        3331373887.5  3975390178.5  3492904185.0  4187480072.0

### 연도별/카테고리별 평균값

In [129]:
category_sum_all = pd.pivot_table(data = purchase_유지,
                                   index = ['BBCL'],
                                   columns = ['PURYEAR'],
                                   values = ['PURAMT'],
                                   aggfunc = 'sum')
category_sum_all

                   PURAMT
PURYEAR              2014          2015
BBCL
가구인테리어/잡화     57885213096   64662169724
가전/레저취미/멀티샵   34406071290   35007569025
교육문화/아동       11552676846   11787712967
식품/생활         94260848777   97178194798
의류/이미용       113928198141  117782175288
침구/주방         14857570518   15116726128

In [138]:
y_cate_mean_df = pd.DataFrame(((cate_sum_2014 + cate_sum_2015)/2).mean(axis = 1))
y_cate_mean_df

                        0
BBCL
가구인테리어/잡화   15318422852.5
가전/레저취미/멀티샵  8676705039.4
교육문화/아동      2917548726.6
식품/생활       23929880446.9
의류/이미용      28963796678.6
침구/주방        3746787080.8

In [143]:
q_cate_mean_df

                        1             2             3             4
BBCL
가구인테리어/잡화   13707045888.0 15397720716.0 13651397171.0 18517527635.0
가전/레저취미/멀티샵  7781721909.5  8912060515.5  7299113878.0 10713923854.5
교육문화/아동      2800774096.0  2910033950.0  2516600850.0  3442786010.5
식품/생활       24421656044.5 22906814423.5 25781027962.0 22610023357.5
의류/이미용      28296468793.5 27652715906.5 23299643212.0 36606358802.5
침구/주방        3331373887.5  3975390178.5  3492904185.0  4187480072.0

In [144]:
13707045888.0/15318422852.5

0.8948079067919829

In [147]:
pd.options.display.float_format = '{:.4f}'.format

q_cate_mean_df.apply(lambda x: x/y_cate_mean_df[0])

                 1      2      3      4
BBCL
가구인테리어/잡화   0.8948 1.0052 0.8912 1.2088
가전/레저취미/멀티샵 0.8969 1.0271 0.8412 1.2348
교육문화/아동     0.9600 0.9974 0.8626 1.1800
식품/생활       1.0206 0.9572 1.0774 0.9448
의류/이미용      0.9770 0.9547 0.8044 1.2639
침구/주방       0.8891 1.0610 0.9322 1.1176

### 가중치 계산

In [156]:
cate_weight = 1/q_cate_mean_df.apply(lambda x: x/y_cate_mean_df[0])
cate_weight

                 1      2      3      4
BBCL
가구인테리어/잡화   1.1176 0.9949 1.1221 0.8272
가전/레저취미/멀티샵 1.1150 0.9736 1.1887 0.8099
교육문화/아동     1.0417 1.0026 1.1593 0.8474
식품/생활       0.9799 1.0447 0.9282 1.0584
의류/이미용      1.0236 1.0474 1.2431 0.7912
침구/주방       1.1247 0.9425 1.0727 0.8948

#### 확인

In [160]:
q_cate_mean_df * cate_weight

,1,2,3,4
BBCL,,,,
가구인테리어/잡화,15318422852.5000,15318422852.5000,15318422852.5000,15318422852.5000
가전/레저취미/멀티샵,8676705039.3750,8676705039.3750,8676705039.3750,8676705039.3750
교육문화/아동,2917548726.6250,2917548726.6250,2917548726.6250,2917548726.6250
식품/생활,23929880446.8750,23929880446.8750,23929880446.8750,23929880446.8750
의류/이미용,28963796678.6250,28963796678.6250,28963796678.6250,28963796678.6250
침구/주방,3746787080.7500,3746787080.7500,3746787080.7500,3746787080.7500

## 카테고리/금액 타입 가중치 계산

In [163]:
category_price_type_sum = pd.pivot_table(data = purchase_유지,
                               index = ['BBCL','PRICE_TYPE'],
                               columns = ['PURYEAR', 'QUARTER'],
                               values = ['PURAMT'],
                               aggfunc = 'sum')
category_price_type_sum

                             PURAMT                                         \
PURYEAR                        2014
QUARTER                           1            2            3            4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가           8460202350   9246488790   8329682030  12018291530
            저가           1325827426   1283622310   1242585400   1796935120
            중가           3007308220   3718391900   3335388990   4120489030
가전/레저취미/멀티샵 고가           3482369570   4278621670   3559997420   4954139610
            저가            375849550    389429950    398868560    437222980
            중가           3838674300   4435172890   3178693430   5077031360
교육문화/아동     고가            128048440    111849410    114853920    286563110
            저가            238378505    213119600    217817314    258182060
            중가           2302887765   2551964445   2177654416   2951357861
식품/생활       고가           7314973493   6069735494   7696666422   6034805125
            저가           2682456348   2814542991   2954196464   3155445076
            중가          13587651258  13907012689  14547165147  13496198270
의류/이미용      고가           7952757820   7750780830   6918048460  10159023780
            저가           1554404357   1748582553   1664080037   2167836535
            중가          17889859281  17435306810  14290062068  24397455610
침구/주방       고가           2134066800   2831586240   2348509850   2767335270
            저가            350020230    342485552    385170430    275298605
            중가            817904020    839287730    785322491    980583300


PURYEAR                        2015
QUARTER                           1            2            3            4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가          10161274860  11638442320  10363698150  14191272830
            저가           1265467040   1162947682   1043377412   1640234640
            중가           3194011880   3745548430   2988062360   3267832120
가전/레저취미/멀티샵 고가           3709270820   4394685920   3946587400   5694390220
            저가            329183159    381398481    339710466    345062569
            중가           3828096420   3944812120   3174370480   4920000970
교육문화/아동     고가            243824379    267408040    251630040    328112250
            저가            237359053    212146410    206149140    199564270
            중가           2451050050   2463579995   2065096870   2861792470
식품/생활       고가           7667326704   5825260481   8169765101   6721091527
            저가           3243744771   3337585054   3336642525   2997965627
            중가          14347159515  13859492138  14857620265  12814541090
의류/이미용      고가           8295847950   7632795740   6899187050   9713149180
            저가           1919385949   1932010630   1848964589   1939960030
            중가          18980682230  18805955250  14978944220  24835292470
침구/주방       고가           2256567240   2776145470   2366162620   3139145350
            저가            244343140    234485655    248286719    221545729
            중가            859846345    926789710    852356260    991051890

In [164]:
category_price_type_sum_2014 = category_price_type_sum.iloc[:,:4]
category_price_type_sum_2014.columns = [1,2,3,4]
category_price_type_sum_2014

                                  1            2            3            4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가           8460202350   9246488790   8329682030  12018291530
            저가           1325827426   1283622310   1242585400   1796935120
            중가           3007308220   3718391900   3335388990   4120489030
가전/레저취미/멀티샵 고가           3482369570   4278621670   3559997420   4954139610
            저가            375849550    389429950    398868560    437222980
            중가           3838674300   4435172890   3178693430   5077031360
교육문화/아동     고가            128048440    111849410    114853920    286563110
            저가            238378505    213119600    217817314    258182060
            중가           2302887765   2551964445   2177654416   2951357861
식품/생활       고가           7314973493   6069735494   7696666422   6034805125
            저가           2682456348   2814542991   2954196464   3155445076
            중가          13587651258  13907012689  14547165147  13496198270
의류/이미용      고가           7952757820   7750780830   6918048460  10159023780
            저가           1554404357   1748582553   1664080037   2167836535
            중가          17889859281  17435306810  14290062068  24397455610
침구/주방       고가           2134066800   2831586240   2348509850   2767335270
            저가            350020230    342485552    385170430    275298605
            중가            817904020    839287730    785322491    980583300

In [165]:
category_price_type_sum_2015 = category_price_type_sum.iloc[:,4:]
category_price_type_sum_2015.columns = [1,2,3,4]
category_price_type_sum_2015

                                  1            2            3            4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가          10161274860  11638442320  10363698150  14191272830
            저가           1265467040   1162947682   1043377412   1640234640
            중가           3194011880   3745548430   2988062360   3267832120
가전/레저취미/멀티샵 고가           3709270820   4394685920   3946587400   5694390220
            저가            329183159    381398481    339710466    345062569
            중가           3828096420   3944812120   3174370480   4920000970
교육문화/아동     고가            243824379    267408040    251630040    328112250
            저가            237359053    212146410    206149140    199564270
            중가           2451050050   2463579995   2065096870   2861792470
식품/생활       고가           7667326704   5825260481   8169765101   6721091527
            저가           3243744771   3337585054   3336642525   2997965627
            중가          14347159515  13859492138  14857620265  12814541090
의류/이미용      고가           8295847950   7632795740   6899187050   9713149180
            저가           1919385949   1932010630   1848964589   1939960030
            중가          18980682230  18805955250  14978944220  24835292470
침구/주방       고가           2256567240   2776145470   2366162620   3139145350
            저가            244343140    234485655    248286719    221545729
            중가            859846345    926789710    852356260    991051890

### 분기별/카테고리별/금액 타입 평균값

In [166]:
pd.options.display.float_format = '{:.1f}'.format
q_cate_type_mean_df = (category_price_type_sum_2014 + category_price_type_sum_2015)/2
q_cate_type_mean_df

                                   1             2             3             4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가          9310738605.0 10442465555.0  9346690090.0 13104782180.0
            저가          1295647233.0  1223284996.0  1142981406.0  1718584880.0
            중가          3100660050.0  3731970165.0  3161725675.0  3694160575.0
가전/레저취미/멀티샵 고가          3595820195.0  4336653795.0  3753292410.0  5324264915.0
            저가           352516354.5   385414215.5   369289513.0   391142774.5
            중가          3833385360.0  4189992505.0  3176531955.0  4998516165.0
교육문화/아동     고가           185936409.5   189628725.0   183241980.0   307337680.0
            저가           237868779.0   212633005.0   211983227.0   228873165.0
            중가          2376968907.5  2507772220.0  2121375643.0  2906575165.5
식품/생활       고가          7491150098.5  5947497987.5  7933215761.5  6377948326.0
            저가          2963100559.5  3076064022.5  3145419494.5  3076705351.5
            중가         13967405386.5 13883252413.5 14702392706.0 13155369680.0
의류/이미용      고가          8124302885.0  7691788285.0  6908617755.0  9936086480.0
            저가          1736895153.0  1840296591.5  1756522313.0  2053898282.5
            중가         18435270755.5 18120631030.0 14634503144.0 24616374040.0
침구/주방       고가          2195317020.0  2803865855.0  2357336235.0  2953240310.0
            저가           297181685.0   288485603.5   316728574.5   248422167.0
            중가           838875182.5   883038720.0   818839375.5   985817595.0

### 연도별/카테고리별 평균값

In [169]:
category_price_type_sum_all = pd.pivot_table(data = purchase_유지,
                                   index = ['BBCL','PRICE_TYPE'],
                                   columns = ['PURYEAR'],
                                   values = ['PURAMT'],
                                   aggfunc = 'sum')
category_price_type_sum_all

                             PURAMT
PURYEAR                        2014         2015
BBCL        PRICE_TYPE
가구인테리어/잡화   고가          38054664700  46354688160
            저가           5648970256   5112026774
            중가          14181578140  13195454790
가전/레저취미/멀티샵 고가          16275128270  17744934360
            저가           1601371040   1395354675
            중가          16529571980  15867279990
교육문화/아동     고가            641314880   1090974709
            저가            927497479    855218873
            중가           9983864487   9841519385
식품/생활       고가          27116180534  28383443813
            저가          11606640879  12915937977
            중가          55538027364  55878813008
의류/이미용      고가          32780610890  32540979920
            저가           7134903482   7640321198
            중가          74012683769  77600874170
침구/주방       고가          10081498160  10538020680
            저가           1352974817    948661243
            중가           3423097541   3630044205

In [183]:
y_cate_type_mean_df = pd.DataFrame((category_price_type_sum_all.iloc[:,0] + category_price_type_sum_all.iloc[:,1])/8)
y_cate_type_mean_df

                                      0
BBCL        PRICE_TYPE
가구인테리어/잡화   고가         10551169107.5000
            저가          1345124628.7500
            중가          3422129116.2500
가전/레저취미/멀티샵 고가          4252507828.7500
            저가           374590714.3750
            중가          4049606496.2500
교육문화/아동     고가           216536198.6250
            저가           222839544.0000
            중가          2478172984.0000
식품/생활       고가          6937453043.3750
            저가          3065322357.0000
            중가         13927105046.5000
의류/이미용      고가          8165198851.2500
            저가          1846903085.0000
            중가         18951694742.3750
침구/주방       고가          2577439855.0000
            저가           287704507.5000
            중가           881642718.2500

In [184]:
q_cate_type_mean_df

                                      1                2                3  \
BBCL        PRICE_TYPE
가구인테리어/잡화   고가          9310738605.0000 10442465555.0000  9346690090.0000
            저가          1295647233.0000  1223284996.0000  1142981406.0000
            중가          3100660050.0000  3731970165.0000  3161725675.0000
가전/레저취미/멀티샵 고가          3595820195.0000  4336653795.0000  3753292410.0000
            저가           352516354.5000   385414215.5000   369289513.0000
            중가          3833385360.0000  4189992505.0000  3176531955.0000
교육문화/아동     고가           185936409.5000   189628725.0000   183241980.0000
            저가           237868779.0000   212633005.0000   211983227.0000
            중가          2376968907.5000  2507772220.0000  2121375643.0000
식품/생활       고가          7491150098.5000  5947497987.5000  7933215761.5000
            저가          2963100559.5000  3076064022.5000  3145419494.5000
            중가         13967405386.5000 13883252413.5000 14702392706.0000
의류/이미용      고가          8124302885.0000  7691788285.0000  6908617755.0000
            저가          1736895153.0000  1840296591.5000  1756522313.0000
            중가         18435270755.5000 18120631030.0000 14634503144.0000
침구/주방       고가          2195317020.0000  2803865855.0000  2357336235.0000
            저가           297181685.0000   288485603.5000   316728574.5000
            중가           838875182.5000   883038720.0000   818839375.5000

                                      4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가         13104782180.0000
            저가          1718584880.0000
            중가          3694160575.0000
가전/레저취미/멀티샵 고가          5324264915.0000
            저가           391142774.5000
            중가          4998516165.0000
교육문화/아동     고가           307337680.0000
            저가           228873165.0000
            중가          2906575165.5000
식품/생활       고가          6377948326.0000
            저가          3076705351.5000
            중가         13155369680.0000
의류/이미용      고가          9936086480.0000
            저가          2053898282.5000
            중가         24616374040.0000
침구/주방       고가          2953240310.0000
            저가           248422167.0000
            중가           985817595.0000

In [144]:
13707045888.0/15318422852.5

0.8948079067919829

In [185]:
pd.options.display.float_format = '{:.4f}'.format

q_cate_type_mean_df.apply(lambda x: x/y_cate_type_mean_df[0])

                            1      2      3      4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가         0.8824 0.9897 0.8858 1.2420
            저가         0.9632 0.9094 0.8497 1.2776
            중가         0.9061 1.0905 0.9239 1.0795
가전/레저취미/멀티샵 고가         0.8456 1.0198 0.8826 1.2520
            저가         0.9411 1.0289 0.9858 1.0442
            중가         0.9466 1.0347 0.7844 1.2343
교육문화/아동     고가         0.8587 0.8757 0.8462 1.4193
            저가         1.0674 0.9542 0.9513 1.0271
            중가         0.9592 1.0119 0.8560 1.1729
식품/생활       고가         1.0798 0.8573 1.1435 0.9194
            저가         0.9667 1.0035 1.0261 1.0037
            중가         1.0029 0.9969 1.0557 0.9446
의류/이미용      고가         0.9950 0.9420 0.8461 1.2169
            저가         0.9404 0.9964 0.9511 1.1121
            중가         0.9728 0.9561 0.7722 1.2989
침구/주방       고가         0.8517 1.0878 0.9146 1.1458
            저가         1.0329 1.0027 1.1009 0.8635
            중가         0.9515 1.0016 0.9288 1.1182

### 가중치 계산

In [186]:
cate_type_weight = 1/q_cate_type_mean_df.apply(lambda x: x/y_cate_type_mean_df[0])
cate_type_weight

                            1      2      3      4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가         1.1332 1.0104 1.1289 0.8051
            저가         1.0382 1.0996 1.1769 0.7827
            중가         1.1037 0.9170 1.0824 0.9264
가전/레저취미/멀티샵 고가         1.1826 0.9806 1.1330 0.7987
            저가         1.0626 0.9719 1.0144 0.9577
            중가         1.0564 0.9665 1.2749 0.8102
교육문화/아동     고가         1.1646 1.1419 1.1817 0.7046
            저가         0.9368 1.0480 1.0512 0.9736
            중가         1.0426 0.9882 1.1682 0.8526
식품/생활       고가         0.9261 1.1664 0.8745 1.0877
            저가         1.0345 0.9965 0.9745 0.9963
            중가         0.9971 1.0032 0.9473 1.0587
의류/이미용      고가         1.0050 1.0615 1.1819 0.8218
            저가         1.0633 1.0036 1.0515 0.8992
            중가         1.0280 1.0459 1.2950 0.7699
침구/주방       고가         1.1741 0.9192 1.0934 0.8727
            저가         0.9681 0.9973 0.9084 1.1581
            중가         1.0510 0.9984 1.0767 0.8943

#### 확인

In [187]:
q_cate_type_mean_df * cate_type_weight

                                      1                2                3  \
BBCL        PRICE_TYPE
가구인테리어/잡화   고가         10551169107.5000 10551169107.5000 10551169107.5000
            저가          1345124628.7500  1345124628.7500  1345124628.7500
            중가          3422129116.2500  3422129116.2500  3422129116.2500
가전/레저취미/멀티샵 고가          4252507828.7500  4252507828.7500  4252507828.7500
            저가           374590714.3750   374590714.3750   374590714.3750
            중가          4049606496.2500  4049606496.2500  4049606496.2500
교육문화/아동     고가           216536198.6250   216536198.6250   216536198.6250
            저가           222839544.0000   222839544.0000   222839544.0000
            중가          2478172984.0000  2478172984.0000  2478172984.0000
식품/생활       고가          6937453043.3750  6937453043.3750  6937453043.3750
            저가          3065322357.0000  3065322357.0000  3065322357.0000
            중가         13927105046.5000 13927105046.5000 13927105046.5000
의류/이미용      고가          8165198851.2500  8165198851.2500  8165198851.2500
            저가          1846903085.0000  1846903085.0000  1846903085.0000
            중가         18951694742.3750 18951694742.3750 18951694742.3750
침구/주방       고가          2577439855.0000  2577439855.0000  2577439855.0000
            저가           287704507.5000   287704507.5000   287704507.5000
            중가           881642718.2500   881642718.2500   881642718.2500

                                      4
BBCL        PRICE_TYPE
가구인테리어/잡화   고가         10551169107.5000
            저가          1345124628.7500
            중가          3422129116.2500
가전/레저취미/멀티샵 고가          4252507828.7500
            저가           374590714.3750
            중가          4049606496.2500
교육문화/아동     고가           216536198.6250
            저가           222839544.0000
            중가          2478172984.0000
식품/생활       고가          6937453043.3750
            저가          3065322357.0000
            중가         13927105046.5000
의류/이미용      고가          8165198851.2500
            저가          1846903085.0000
            중가         18951694742.3750
침구/주방       고가          2577439855.0000
            저가           287704507.5000
            중가           881642718.2500

### 유지고객 데이터 내 고객별/분기별/카테고리별/금액타입별로 나누기

In [194]:
def pivot(df, aggfunc):
    # 분기 변경
#     df['Q_year'] = df['PURYEAR'].astype(str)+ '_' + df['QUARTER'].astype(str)
#     df['Q_year']

#     # 년도
#     pivot_df_year = pd.pivot_table(df,
#                              values = 'PURAMT',
#                              index = 'CUSTNO',
#                              columns = ['PURYEAR', 'BBCL', 'PRICE_TYPE'],
#                              aggfunc = aggfunc)
#     pivot_df_year.fillna(0, inplace = True)
#     columns_name = []
#     for indexs in pivot_df_year.columns:
#          columns_name.append('_'.join([aggfunc] + [str(idx) for idx in indexs]))
#     pivot_df_year.columns = columns_name
    
#     # 년도 총액
#     pivot_df_label_year = pd.pivot_table(df,
#                                         values = 'PURAMT',
#                                         index = 'CUSTNO',
#                                         columns = ['PURYEAR'],
#                                         aggfunc = 'sum')
#     pivot_df_label_year.fillna(0, inplace = True)
    
#     # 반기
#     pivot_df_half = pd.pivot_table(df,
#                                      values = 'PURAMT',
#                                      index = 'CUSTNO',
#                                      columns = ['HALF_YEAR', 'BBCL', 'PRICE_TYPE'],
#                                      aggfunc = aggfunc) # 대분류하는것
#     pivot_df_half.fillna(0, inplace = True)
#     # 컬럼 변경
#     columns_name = []
#     for indexs in pivot_df_half.columns:
#          columns_name.append('_'.join([aggfunc, '반기'] + [str(idx) for idx in indexs]))
#     pivot_df_half.columns = columns_name
    
#     # 반기 총액
#     pivot_df_label_half = pd.pivot_table(df,
#                                         values = 'PURAMT',
#                                         index = 'CUSTNO',
#                                         columns = ['HALF_YEAR'],
#                                         aggfunc = 'sum')
#     pivot_df_label_half.fillna(0, inplace = True)
    
    # 분기
    pivot_df_q_ = pd.pivot_table(df,
                               values = 'PURAMT',
                               index = 'CUSTNO',
                               columns = ['Q_year', 'BBCL', 'PRICE_TYPE'],
                               aggfunc = aggfunc)
    pivot_df_q_.fillna(0, inplace = True)
    # 컬럼 변경
    columns_name = []
    for indexs in pivot_df_q_.columns:
         columns_name.append('_'.join([aggfunc, '분기'] + [str(idx) for idx in indexs]))
    pivot_df_q_.columns = columns_name
    
    # 분기 총액
    pivot_df_label_q = pd.pivot_table(df,
                                values = 'PURAMT',
                                index = 'CUSTNO',
                                columns = ['Q_year'],
                                aggfunc = 'sum')
    pivot_df_label_q.fillna(0, inplace = True)
    
#     pivot_total_ = pd.concat([pivot_df_year, pivot_df_half, pivot_df_q_], axis = 1)  
#     def minus(x):
#         if x > 0: y = 1
#         else: y = 0
#         return y
  
#     # 년도기준 증가
#     pivot_total_['year_up'] = pivot_df_label_year[2015] -  pivot_df_label_year[2014]
#     pivot_total_['year_label'] = pivot_total_['year_up'].apply(lambda x : minus(x))
#     # 반기기준 증가
#     pivot_total_['half_up'] = pivot_df_label_half[4] -  pivot_df_label_half[1]
#     pivot_total_['half_label'] = pivot_total_['half_up'].apply(lambda x : minus(x))
#     # 분기기준 증가
#     pivot_total_['q_up'] = pivot_df_label_q['2015_4'] -  pivot_df_label_q['2014_1']
#     pivot_total_['q_label'] = pivot_total_['q_up'].apply(lambda x : minus(x))
    
#     total_df = pivot_total_.copy()
    return pivot_df_q_

In [206]:
df_sum = pivot(purchase_유지, 'sum')
df_sum

,sum_분기_2014_1_가구인테리어/잡화_고가,sum_분기_2014_1_가구인테리어/잡화_저가,sum_분기_2014_1_가구인테리어/잡화_중가,sum_분기_2014_1_가전/레저취미/멀티샵_고가,sum_분기_2014_1_가전/레저취미/멀티샵_저가,sum_분기_2014_1_가전/레저취미/멀티샵_중가,sum_분기_2014_1_교육문화/아동_고가,sum_분기_2014_1_교육문화/아동_저가,sum_분기_2014_1_교육문화/아동_중가,sum_분기_2014_1_식품/생활_고가,...,sum_분기_2015_4_교육문화/아동_중가,sum_분기_2015_4_식품/생활_고가,sum_분기_2015_4_식품/생활_저가,sum_분기_2015_4_식품/생활_중가,sum_분기_2015_4_의류/이미용_고가,sum_분기_2015_4_의류/이미용_저가,sum_분기_2015_4_의류/이미용_중가,sum_분기_2015_4_침구/주방_고가,sum_분기_2015_4_침구/주방_저가,sum_분기_2015_4_침구/주방_중가
CUSTNO,,,,,,,,,,,,,,,,,,,,,
1,0.0000,390800.0000,0.0000,641250.0000,0.0000,65550.0000,0.0000,0.0000,103740.0000,1027500.0000,...,0.0000,237618.0000,5540.0000,346870.0000,133100.0000,0.0000,3415160.0000,137750.0000,0.0000,699200.0000
2,0.0000,562170.0000,150000.0000,2194330.0000,30500.0000,0.0000,0.0000,0.0000,113920.0000,519290.0000,...,0.0000,264720.0000,0.0000,1481370.0000,5896250.0000,0.0000,3002000.0000,0.0000,0.0000,432490.0000
3,0.0000,600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,21800.0000,...,0.0000,0.0000,146169.0000,102132.0000,0.0000,7800.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,191810.0000,189520.0000,0.0000,0.0000,141550.0000,0.0000,0.0000,0.0000,8000.0000,...,0.0000,113357.0000,44688.0000,617760.0000,0.0000,90000.0000,565980.0000,0.0000,0.0000,54000.0000
6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,265680.0000,...,0.0000,329241.0000,134399.0000,705709.0000,975000.0000,157140.0000,645900.0000,0.0000,3800.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0000,0.0000,0.0000,0.0000,22000.0000,0.0000,0.0000,3000.0000,22700.0000,34440.0000,...,0.0000,12300.0000,28650.0000,479480.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19334,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7000.0000,11250.0000,0.0000,...,119200.0000,7990.0000,52550.0000,66170.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19335,0.0000,25000.0000,0.0000,0.0000,0.0000,0.0000,82800.0000,28400.0000,103324.0000,72130.0000,...,684480.0000,38480.0000,99865.0000,829819.0000,0.0000,188500.0000,0.0000,0.0000,6000.0000,0.0000
19336,0.0000,0.0000,0.0000,0.0000,0.0000,387000.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,318600.0000,172200.0000,13000.0000,2624640.0000,159000.0000,0.0000,0.0000
19337,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,38890.0000,367640.0000,479480.0000,0.0000,2990.0000,79000.0000,0.0000,0.0000,0.0000

In [234]:
df_sum_q1 = df_sum.iloc[:,:18]
df_sum_q1.columns = cate_type_weight_final.columns
df_sum_q1

BBCL_PRICE_TYPE,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가
CUSTNO,,,,,,,,,,,,,,,,,,
1,0.0000,390800.0000,0.0000,641250.0000,0.0000,65550.0000,0.0000,0.0000,103740.0000,1027500.0000,0.0000,759320.0000,2395640.0000,0.0000,3110080.0000,177650.0000,0.0000,470060.0000
2,0.0000,562170.0000,150000.0000,2194330.0000,30500.0000,0.0000,0.0000,0.0000,113920.0000,519290.0000,0.0000,2387950.0000,6630010.0000,0.0000,325500.0000,1073900.0000,0.0000,135900.0000
3,0.0000,600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,21800.0000,179883.0000,100499.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,191810.0000,189520.0000,0.0000,0.0000,141550.0000,0.0000,0.0000,0.0000,8000.0000,6400.0000,593513.0000,33250.0000,18000.0000,79600.0000,0.0000,0.0000,48000.0000
6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,265680.0000,345298.0000,521018.0000,440000.0000,90600.0000,414700.0000,0.0000,53710.0000,35000.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0000,0.0000,0.0000,0.0000,22000.0000,0.0000,0.0000,3000.0000,22700.0000,34440.0000,33580.0000,448510.0000,0.0000,0.0000,43000.0000,0.0000,5900.0000,0.0000
19334,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7000.0000,11250.0000,0.0000,63707.0000,707092.0000,0.0000,45000.0000,0.0000,0.0000,0.0000,0.0000
19335,0.0000,25000.0000,0.0000,0.0000,0.0000,0.0000,82800.0000,28400.0000,103324.0000,72130.0000,36230.0000,271420.0000,0.0000,45000.0000,0.0000,0.0000,273430.0000,0.0000
19336,0.0000,0.0000,0.0000,0.0000,0.0000,387000.0000,0.0000,0.0000,0.0000,0.0000,0.0000,62600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19337,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7740.0000,8780.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [ ]:
df_sum_q1.columns =

In [209]:
df_sum_q2 = df_sum.iloc[:,18:36]
df_sum_q2

,sum_분기_2014_2_가구인테리어/잡화_고가,sum_분기_2014_2_가구인테리어/잡화_저가,sum_분기_2014_2_가구인테리어/잡화_중가,sum_분기_2014_2_가전/레저취미/멀티샵_고가,sum_분기_2014_2_가전/레저취미/멀티샵_저가,sum_분기_2014_2_가전/레저취미/멀티샵_중가,sum_분기_2014_2_교육문화/아동_고가,sum_분기_2014_2_교육문화/아동_저가,sum_분기_2014_2_교육문화/아동_중가,sum_분기_2014_2_식품/생활_고가,sum_분기_2014_2_식품/생활_저가,sum_분기_2014_2_식품/생활_중가,sum_분기_2014_2_의류/이미용_고가,sum_분기_2014_2_의류/이미용_저가,sum_분기_2014_2_의류/이미용_중가,sum_분기_2014_2_침구/주방_고가,sum_분기_2014_2_침구/주방_저가,sum_분기_2014_2_침구/주방_중가
CUSTNO,,,,,,,,,,,,,,,,,,
1,0.0000,361020.0000,1013850.0000,1436400.0000,0.0000,0.0000,0.0000,0.0000,73720.0000,2462585.0000,750.0000,519600.0000,1370900.0000,0.0000,3544940.0000,0.0000,0.0000,0.0000
2,0.0000,481270.0000,311690.0000,1510780.0000,0.0000,244650.0000,0.0000,0.0000,352460.0000,679510.0000,0.0000,1767280.0000,2720530.0000,0.0000,786340.0000,1229930.0000,0.0000,115320.0000
3,0.0000,1500.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,24470.0000,264843.0000,177620.0000,0.0000,0.0000,80000.0000,0.0000,0.0000,0.0000
4,0.0000,137200.0000,331000.0000,119000.0000,5200.0000,141550.0000,0.0000,0.0000,0.0000,65174.0000,63100.0000,907439.0000,737000.0000,15000.0000,1204800.0000,0.0000,6000.0000,0.0000
6,39000.0000,102000.0000,292800.0000,0.0000,14800.0000,0.0000,0.0000,0.0000,0.0000,204582.0000,229124.0000,670778.0000,359000.0000,121000.0000,930000.0000,105000.0000,47200.0000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0000,1500.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,25600.0000,109200.0000,29770.0000,747918.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19334,0.0000,0.0000,0.0000,0.0000,15900.0000,0.0000,0.0000,31750.0000,32780.0000,101103.0000,308308.0000,2137496.0000,0.0000,42980.0000,0.0000,0.0000,35600.0000,0.0000
19335,0.0000,57300.0000,0.0000,0.0000,82000.0000,62000.0000,73000.0000,314700.0000,206540.0000,362480.0000,162900.0000,841152.0000,0.0000,374410.0000,43200.0000,0.0000,156640.0000,46800.0000
19336,0.0000,49000.0000,56000.0000,0.0000,0.0000,8900.0000,0.0000,0.0000,0.0000,670400.0000,0.0000,535220.0000,344300.0000,24900.0000,1575150.0000,0.0000,0.0000,58000.0000
19337,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,33160.0000,38810.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

### 가중치 곱해주기

In [214]:
cate_type_weight_reset_idx.columns

Index(['BBCL', 'PRICE_TYPE', 1, 2, 3, 4], dtype='object')

In [219]:
cate_type_weight_reset_idx = cate_type_weight.reset_index()
cate_type_weight_reset_idx['BBCL_PRICE_TYPE'] = cate_type_weight_reset_idx['BBCL'] + '_' + cate_type_weight_reset_idx['PRICE_TYPE']
cate_type_weight_reset_idx.drop(columns = ['BBCL', 'PRICE_TYPE'], inplace = True)
cate_type_weight_final = cate_type_weight_reset_idx.set_index('BBCL_PRICE_TYPE').transpose()
cate_type_weight_final

BBCL_PRICE_TYPE,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가
1,1.1332,1.0382,1.1037,1.1826,1.0626,1.0564,1.1646,0.9368,1.0426,0.9261,1.0345,0.9971,1.0050,1.0633,1.0280,1.1741,0.9681,1.0510
2,1.0104,1.0996,0.9170,0.9806,0.9719,0.9665,1.1419,1.0480,0.9882,1.1664,0.9965,1.0032,1.0615,1.0036,1.0459,0.9192,0.9973,0.9984
3,1.1289,1.1769,1.0824,1.1330,1.0144,1.2749,1.1817,1.0512,1.1682,0.8745,0.9745,0.9473,1.1819,1.0515,1.2950,1.0934,0.9084,1.0767
4,0.8051,0.7827,0.9264,0.7987,0.9577,0.8102,0.7046,0.9736,0.8526,1.0877,0.9963,1.0587,0.8218,0.8992,0.7699,0.8727,1.1581,0.8943

In [237]:
df_sum_q1

BBCL_PRICE_TYPE,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가
CUSTNO,,,,,,,,,,,,,,,,,,
1,0.0000,390800.0000,0.0000,641250.0000,0.0000,65550.0000,0.0000,0.0000,103740.0000,1027500.0000,0.0000,759320.0000,2395640.0000,0.0000,3110080.0000,177650.0000,0.0000,470060.0000
2,0.0000,562170.0000,150000.0000,2194330.0000,30500.0000,0.0000,0.0000,0.0000,113920.0000,519290.0000,0.0000,2387950.0000,6630010.0000,0.0000,325500.0000,1073900.0000,0.0000,135900.0000
3,0.0000,600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,21800.0000,179883.0000,100499.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,191810.0000,189520.0000,0.0000,0.0000,141550.0000,0.0000,0.0000,0.0000,8000.0000,6400.0000,593513.0000,33250.0000,18000.0000,79600.0000,0.0000,0.0000,48000.0000
6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,265680.0000,345298.0000,521018.0000,440000.0000,90600.0000,414700.0000,0.0000,53710.0000,35000.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0000,0.0000,0.0000,0.0000,22000.0000,0.0000,0.0000,3000.0000,22700.0000,34440.0000,33580.0000,448510.0000,0.0000,0.0000,43000.0000,0.0000,5900.0000,0.0000
19334,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7000.0000,11250.0000,0.0000,63707.0000,707092.0000,0.0000,45000.0000,0.0000,0.0000,0.0000,0.0000
19335,0.0000,25000.0000,0.0000,0.0000,0.0000,0.0000,82800.0000,28400.0000,103324.0000,72130.0000,36230.0000,271420.0000,0.0000,45000.0000,0.0000,0.0000,273430.0000,0.0000
19336,0.0000,0.0000,0.0000,0.0000,0.0000,387000.0000,0.0000,0.0000,0.0000,0.0000,0.0000,62600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19337,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7740.0000,8780.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [252]:
df_sum_q1

BBCL_PRICE_TYPE,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가
CUSTNO,,,,,,,,,,,,,,,,,,
1,0.0000,390800.0000,0.0000,641250.0000,0.0000,65550.0000,0.0000,0.0000,103740.0000,1027500.0000,0.0000,759320.0000,2395640.0000,0.0000,3110080.0000,177650.0000,0.0000,470060.0000
2,0.0000,562170.0000,150000.0000,2194330.0000,30500.0000,0.0000,0.0000,0.0000,113920.0000,519290.0000,0.0000,2387950.0000,6630010.0000,0.0000,325500.0000,1073900.0000,0.0000,135900.0000
3,0.0000,600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,21800.0000,179883.0000,100499.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,191810.0000,189520.0000,0.0000,0.0000,141550.0000,0.0000,0.0000,0.0000,8000.0000,6400.0000,593513.0000,33250.0000,18000.0000,79600.0000,0.0000,0.0000,48000.0000
6,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,265680.0000,345298.0000,521018.0000,440000.0000,90600.0000,414700.0000,0.0000,53710.0000,35000.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0000,0.0000,0.0000,0.0000,22000.0000,0.0000,0.0000,3000.0000,22700.0000,34440.0000,33580.0000,448510.0000,0.0000,0.0000,43000.0000,0.0000,5900.0000,0.0000
19334,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7000.0000,11250.0000,0.0000,63707.0000,707092.0000,0.0000,45000.0000,0.0000,0.0000,0.0000,0.0000
19335,0.0000,25000.0000,0.0000,0.0000,0.0000,0.0000,82800.0000,28400.0000,103324.0000,72130.0000,36230.0000,271420.0000,0.0000,45000.0000,0.0000,0.0000,273430.0000,0.0000
19336,0.0000,0.0000,0.0000,0.0000,0.0000,387000.0000,0.0000,0.0000,0.0000,0.0000,0.0000,62600.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
19337,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,7740.0000,8780.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000