In [2]:
import pandas as pd

df =pd.read_csv('cleanlivedf201911.csv',index_col = 0)
df['법정동명'] == '청운'

     시군구명     법정동코드 법정동명     연령대  거주인구수/n
0     강남구  11680101  역삼동     10대  63336.0
1     강남구  11680101  역삼동  10대 미만  39924.0
2     강남구  11680101  역삼동     20대  73092.0
3     강남구  11680101  역삼동     30대  78416.0
4     강남구  11680101  역삼동     40대  92848.0
...   ...       ...  ...     ...      ...
8587  중랑구  11260106  신내동     30대  57522.0
8588  중랑구  11260106  신내동     40대  57668.0
8589  중랑구  11260106  신내동     50대  71920.0
8590  중랑구  11260106  신내동     60대  56140.0
8591  중랑구  11260106  신내동  70대 이상  48758.0

[8592 rows x 5 columns]

In [7]:

df = pd.read_csv('clean_map_live_df_b.csv',index_col = 0)
df[df['법정동명'].isin(['청운동'])].groupby(['시군구명','법정동코드','법정동명']).sum()

                      법정동단위 거주인구
시군구명 법정동코드      법정동명
종로구  1111010100 청운동       1199.7